# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [40]:
! pip install -U chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.13/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.2.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.12.2)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)

## **Importing libraries**

In [41]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for coronavirus**

In [42]:
# Target search for coronavirus
# it should produce same results as https://www.ebi.ac.uk/chembl/search_results/coronavirus?focusEntity=targets
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,14.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,14.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,14.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,14.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],unidentified human coronavirus,unidentified human coronavirus,13.0,False,CHEMBL6195448,[],ORGANISM,694448
8,[],Human coronavirus NL63,Human coronavirus NL63,13.0,False,CHEMBL6195756,[],ORGANISM,277944
9,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,9.0,False,CHEMBL4296578,[],ORGANISM,1335626
10,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
11,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
12,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,4.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
13,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon/Replicase polyprotein 1ab,4.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
14,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,4.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

### **Select and retrieve bioactivity data for *SARS coronavirus 3C-like proteinase* (fifth entry)**

We will assign the fifth entry (which corresponds to the target protein, *coronavirus 3C-like proteinase*) to the ***selected_target*** variable

In [43]:
t_id = 12
selected_target = targets.target_chembl_id[t_id]
selected_target

'CHEMBL4523582'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [44]:
# it is = https://www.ebi.ac.uk/chembl/explore/activities/STATE_ID:fnJwd_c6pYPq67sEoJC7qw%3D%3D
# Activity records describe experimental measurements between a molecule and a biological target.
activity = new_client.activity
# From those activities, keep only measurements whose standard type is IC50.
# IC50 tells you how much of a drug you need to inhibit a target by 50%. Eg.:
# Drug A: IC50 = 5 nM
# Drug B: IC50 = 500 nM
# Drug A is more potent than Drug B.
# res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")
res = new_client.activity.filter(
    target_chembl_id=selected_target,
    standard_type="IC50",
    standard_relation="=",           # drop censored values at the server
).only(["molecule_chembl_id", "canonical_smiles", "standard_type",
        "standard_value", "standard_units", "assay_description"])
# Just to read it...
print(type(res)) # chembl_webresource_client.query_set.QuerySet

# for r in res:
#     print(r["molecule_chembl_id"], r["standard_value"])

<class 'chembl_webresource_client.query_set.QuerySet'>

In [47]:
# chembl_webresource_client.query_set.QuerySet is lazy. So download 1 shot in a list (and reuse if needed)
# use tqdm to track the download (important in case of large dataset)
from tqdm import tqdm
records = list(tqdm(res, desc="Downloading ChEMBL records..."))
df = pd.DataFrame.from_dict(records)

Downloading ChEMBL records: 100%|██████████| 4881/4881 [02:49<00:00, 28.81it/s]

In [48]:
df.head(3)

,assay_description,canonical_smiles,molecule_chembl_id,standard_type,standard_units,standard_value,type,units,value
0,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1,CHEMBL480,IC50,nM,390.0,IC50,uM,0.39
1,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,Cc1c(-c2cnccn2)ssc1=S,CHEMBL178459,IC50,nM,210.0,IC50,uM,0.21
2,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1,CHEMBL3545157,IC50,nM,80.0,IC50,uM,0.08

In [49]:
# check that IC50 is unique value
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [50]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [ ]:
#from google.colab import drive
#drive.mount('/content/gdrive/', force_remount=True)

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [ ]:
#! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"
# ! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
# ! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

Let's see the CSV files that we have so far.

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [ ]:
! head bioactivity_data.csv

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [51]:
df2 = df[df.standard_value.notna()]
df2

,assay_description,canonical_smiles,molecule_chembl_id,standard_type,standard_units,standard_value,type,units,value
0,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1,CHEMBL480,IC50,nM,390.0,IC50,uM,0.39
1,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,Cc1c(-c2cnccn2)ssc1=S,CHEMBL178459,IC50,nM,210.0,IC50,uM,0.21
2,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1,CHEMBL3545157,IC50,nM,80.0,IC50,uM,0.08
3,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,O=C(O[C@@H]1Cc2c(O)cc(O)cc2O[C@@H]1c1cc(O)c(O)...,CHEMBL297453,IC50,nM,1580.0,IC50,uM,1.58
4,SARS-CoV-2 3CL-Pro protease inhibition IC50 de...,O=C1C=Cc2cc(Br)ccc2C1=O,CHEMBL4303595,IC50,nM,40.0,IC50,uM,0.04
...,...,...,...,...,...,...,...,...,...
4876,Inhibition of SARS-CoV-2 nsp13 by FRET assay,COc1ccc(/C=N/NC(=O)c2ccc(CSc3cccc4cccnc34)cc2)cc1,CHEMBL6193634,IC50,nM,960.0,IC50,uM,0.96
4877,Inhibition of SARS-CoV-2 nsp13 by FRET assay,O=C(N/N=C/c1cc(F)c(F)cc1O)c1ccc(CSc2cccc3cccnc...,CHEMBL6191170,IC50,nM,2340.0,IC50,uM,2.34
4878,Inhibition of SARS-CoV-2 nsp13 by FRET assay,O=C(N/N=C/c1cc(O)c(Br)c(O)c1)c1ccc(CSc2cccc3cc...,CHEMBL6191510,IC50,nM,2060.0,IC50,uM,2.06
4879,Inhibition of SARS-CoV-2 nsp13 by FRET assay,O=C(N/N=C/c1cc([N+](=O)[O-])ccc1Cl)c1ccc(CSc2c...,CHEMBL6193155,IC50,nM,280.0,IC50,uM,0.28
4880,Inhibition of SARS-CoV-2 nsp13 by FRET assay,O=C(N/N=C/c1cc([N+](=O)[O-])ccc1Cl)c1ccc(CSc2c...,CHEMBL6188867,IC50,nM,760.0,IC50,uM,0.76

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [52]:
bioactivity_class = []
for i in df2.standard_value:
  print(i)
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

390.0
210.0
80.0
1580.0
40.0
3190.0
360.0
200.0
100.0
160.0
4530.0
1330.0
140.0
220.0
150.0
140.0
2800.0
10.0
1600.0
540.0
390.0
20.0
50.0
190.0
160.0
2040.0
4220.0
2050.0
3190.0
3170.0
1370.0
150.0
2360.0
1080.0
4580.0
3380.0
2570.0
210.0
1590.0
740.0
970.0
1120.0
140.0
140.0
3550.0
670.0
2590.0
2630.0
1740.0
1870.0
3020.0
180.0
230.0
2990.0
1990.0
1490.0
820.0
2460.0
3420.0
3860.0
240.0
1320.0
240.0
50.0
30.0
980.0
3660.0
1050.0
30.0
220.0
240.0
420.0
3990.0
160.0
4540.0
940.0
510.0
290.0
840.0
580.0
400.0
840.0
330.0
2070.0
4950.0
2250.0
480.0
410.0
1740.0
720.0
10.0
1330.0
770.0
4380.0
830.0
580.0
3820.0
20.0
2350.0
300.0
10.0
520.0
220.0
1140.0
210.0
150.0
620.0
1720.0
4360.0
1240.0
4980.0
750.0
880.0
1930.0
94.0
286.0
14.0
23.0
65.0
42.0
34.0
8.0
9.0
53.0
40.0
31.0
31.0
4130.0
10690.0
30.0
3140.0
3900.0
4810.0
11470.0
71000.0
110.0
450.0
85.0
63.0
26920.0
12300.0
8910.0
9820.0
7500.0
6810.0
7940.0
9080.0
7640.0
6680.0
8710.0
7210.0
10720.0
9770.0
10010.0
8710.0
7080.0
4550.0
1560.0
4730.0
20890.0
7080.0
3350.0
4550.0
1190.0
1650.0
3760.0
1110.0
4010.0
5370.0
3110.0
2180.0
3850.0
1890.0
180.0
2390.0
180.0
2390.0
180.0
670.0
124930.0
1820.0
670.0
15750.0
9350.0
21390.0
1550.0
940.0
939.72
6410.0
4130.0
30.0
970.0
450.0
180.0
2390.0
670.0
53.0
40.0
5730.0
3900.0
10690.0
8600.0
3140.0
125025.9
1819.7
669.88
15739.83
9354.06
21379.62
1548.82
6412.1
4130.48
29.99
970.51
449.78
179.89
2387.81
669.88
52.97
39.99
5727.96
3899.42
10690.55
8590.14
3140.51
450.0
970.0
30.0
4130.0
940.0
6410.0
40.0
53.0
2400.0
5000.0
23500.0
100700.0
38000.0
27000.0
33000.0
4200.0
4100.0
15000.0
33.0
75.0
5.0
8.0
0.4
0.013
5.1
0.44
0.44
0.79
0.61
2.98
0.35
0.4
0.59
0.48
4200.0
18.0
50.0
430.0
7300.0
1610.0
1010.0
590.0
820.0
700.0
640.0
330.0
620.0
760.0
970.0
810.0
170.0
370.0
640.0
210.0
430.0
113.0
250.0
2400.0
56000.0
600.0
700.0
800.0
12700.0
6400.0
5100.0
7000.0
16800.0
43200.0
7500.0
10000.0
10000.0
7600.0
15000.0
42000.0
7290.0
6670.0
620.0
660.0
670.0
870.0
900.0
800.0
580.0
990.0
670.0
6970.0
2640.0
2690.0
4320.0
1760.0
3750.0
1370.0
820.0
800.0
440.0
2670.0
1750.0
2000.0
1850.0
1130.0
2160.0
1520.0
580.0
780.0
260.0
120.0
380.0
670.0
9.5
3.8
28.0
4.8
15.6
464.0
332.0
1.7
0.79
24200.0
62200.0
35100.0
29900.0
32400.0
26700.0
36500.0
29500.0
14900.0
52900.0
53900.0
55800.0
29500.0
52500.0
35800.0
30800.0
27700.0
46100.0
24200.0
12100.0
54000.0
19.0
11.0
4.8
5.2
150.0
60.0
36.0
13.0
16.0
77.0
49.0
350.0
8.4
650.0
530.0
160.0
52.0
66.0
30.0
8.5
15.0
33.0
60.0
47.0
105.0
17.9
23.0
9.3
40.0
360.0
620.0
75.0
370.0
720.0
120.0
23.0
17.0
26.0
180.0
150.0
22.0
45.0
59.0
97.0
120.0
720.0
66.0
4200.0
8000.0
10000.0
13900.0
6100.0
56900.0
52300.0
17200.0
1700.0
38500.0
59800.0
10300.0
9400.0
7700.0
21000.0
10.0
19.0
14.0
9.0
5.0
10.0
15.0
5.0
10.0
780.0
6.0
4.0
14.0
2.0
12.0
9.0
360.0
100.0
140.0
260.0
190.0
13.0
40.0
60.0
19.5
49.0
13.7
24.0
14.0
9.1
18.9
4600.0
3660.0
75010.0
1500.0
1500.0
1500.0
7500.0
8100.0
5100.0
5600.0
5600.0
420.0
1410.0
46.0
34.0
8.0
540.0
87.0
5.0
17.0
17.0
1200.0
53.0
2.0
7.0
4.0
3.0
14.0
2.0
4.0
143.0
624.0
60.0
72.3
54.7
159.0
349.0
91.4
147.0
1220.0
281.0
316.0
481.0
34.4
250.0
235.0
454.0
11.4
87.6
2030.0
18.1
288.0
15.5
13.7
14.4
20.6
551.0
117.0
166.0
255.0
190.0
125.0
88.9
313.0
34.2
2350.0
2080.0
4030.0
710.0
670.0
1340.0
900.0
53.0
40.0
30.0
940.0
6410.0
1100.0
340.0
670.0
240.0
10000.0
10000.0
2260.0
240.0
260.0
34000.0
260.0
600.0
4350.0
1390.0
1789.0
1336.0
590.0
1571.0
260.0
530.0
390.0
610.0
440.0
2690.0
7290.0
6670.0
670.0
670.0
2300.0
5100.0
6400.0
7000.0
12700.0
810.0
2100.0
11000.0
3760.0
6680.0
3990.0
1660.0
1460.0
500.0
1000.0
100.0
72000.0
560.0
2470.0
5630.0
2210.0
1650.0
7240.0
1700.0
2200.0
3100.0
66000.0
13160.0
16080.0
15680.0
17510.0
94.0
230.0
98.0
5400.0
8000.0
2020.0
236.0
256.0
339.0
263.0
1255.0
578.0
1885.0
990.0
2067.0
1038.0
1288.0
25.69
49.55
27.95
52.5
15.24
37.81
27.37
7520.0
858.0
3889.0
374.0
373.0
277.0
271.0
209.0
321.0
298.0
1497.0
12320.0
6928.0
3436.0
2044.0
1338.0
3275.0
543.0
357.0
281.0
196.0
230.0
295.0
249.0
592.0
307.0
173.0
255.0
295.0
221.0
199.0
257.0
404.0
1409.0
234.0
173.0
172.0
153.0
640.0
565.0
197.0
148.0
1426.0
285.0
21280.0
300.0
25020.0
17500.0
10760.0
8080.0
9690.0
10880.0
17530.0
9090.0
4140.0
5810.0
7090.0
8760.0
10400.0
10300.0
1550.0
4000.0
5390.0
4050.0
8140.0
4690.0
1570.0
32530.0
40590.0
25390.0
10000.0
24560.0
5780.0
5440.0
42760.0
6180.0
850.0
670.0
670.0
53.0
4130.0
30.0
15.0
940.0
2500.0
31.0
10.0
8.0
44.0
19.0
27.0
27.0
540.0
1800.0
630.0
190.0
190.0
160.0
400.0
380.0
190.0
140.0
150.0
180.0
150.0
300.0
120.0
310.0
334.8
250.0
210.0
2293.0
220.2
1571.3
230.0
388.3
680.0
253.0
539.9
165.2
116.8
286.7
328.0
333.5
153.1
286.6
224.2
392.7
524.02
1767.0
416.0
443.1
10977.0
490.0
6400.0
7900.0
15300.0
11.2
6800.0
138000.0
38900.0
125300.0
9600.0
2700.0
61.0
69.0
440.0
48.0
93.0
260.0
100.0
100.0
100.0
100.0
2390.0
670.0
1600.0
180.0
310.0
2800.0
400.0
5100.0
92.0
0.27
530.0
670.0
8.0
30.0
10960.0
670.0
120.0
990.0
40.0
670.0
390.0
256.0
260.0
1390.0
94.0
200.0
280.0
510.0
560.0
660.0
670.0
810.0
940.0
960.0
1050.0
1480.0
1810.0
1970.0
2140.0
2390.0
2470.0
2510.0
2540.0
2680.0
3860.0
4100.0
4930.0
4970.0
5370.0
5460.0
5700.0
5820.0
7270.0
7490.0
7810.0
8130.0
10960.0
12090.0
13240.0
21880.0
35100.0
190.0
64.1
21.9
20.0
12.5
86.3
63.5
6.4
1.0
125.5
4.0
32.9
19.0
14.0
22.1
71.5
19.5
1500.0
17.0
61150.0
33060.0
29460.0
9060.0
6440.0
19320.0
11390.0
85580.0
57670.0
53810.0
58910.0
68160.0
5650.0
66800.0
35770.0
18500.0
14170.0
11970.0
13820.0
8540.0
2460.0
9820.0
4790.0
10260.0
3320.0
10000.0
11230.0
7390.0
5250.0
4290.0
2720.0
6730.0
2780.0
8890.0
6650.0
5830.0
3660.0
8280.0
3310.0
1550.0
1810.0
10230.0
5390.0
4710.0
10680.0
5500.0
1040.0
17660.0
5440.0
3200.0
7810.0
4060.0
7120.0
5920.0
5790.0
5350.0
5320.0
10490.0
6720.0
19090.0
36070.0
8500.0
54.0
13.0
8600.0
96.0
14100.0
5100.0
1400.0
3500.0
2100.0
5000.0
3589.0
4400.0
2900.0
342.0
244.0
146.0
516.0
80.0
38.0
44.0
5300.0
899.0
1010.0
514.0
960.0
19.0
13020.0
482.0
344.0
442.0
100.0
56.0
114.0
80.0
30.0
278.0
360.0
6600.0
26100.0
5800.0
9200.0
7400.0
16900.0
3600.0
1600.0
35300.0
13300.0
31100.0
10200.0
9000.0
7900.0
5200.0
3000.0
9700.0
6600.0
45700.0
5300.0
2800.0
2300.0
4100.0
42100.0
700.0
10100.0
24200.0
600.0
500.0
22900.0
3300.0
850.0
1150.0
650.0
260.0
260.0
680.0
450.0
750.0
760.0
1250.0
1200.0
360.0
290.0
380.0
410.0
350.0
290.0
240.0
240.0
320.0
390.0
410.0
2500.0
3050.0
3650.0
2500.0
410.0
500.0
830.0
760.0
520.0
490.0
4950.0
4050.0
330.0
340.0
180.0
170.0
290.0
290.0
310.0
260.0
280.0
300.0
260.0
280.0
140.0
100.0
1900.0
1710.0
390.0
370.0
270.0
300.0
310.0
310.0
180.0
150.0
290.0
270.0
270.0
250.0
820.0
1030.0
740.0
780.0
670.0
50.0
40.0
670.0
670.0
670.0
670.0
670.0
670.0
260.0
11390.0
9840.0
10700.0
53.0
40.0
400.0
190.0
45.0
45.0
970.0
16.0
15.2
7.6
17.2
2860.0
86320.0
7960.0
490.0
200.0
430.0
80.0
56.0
530.0
14.0
830.0
19.2
55.0
34.2
27.95
15.24
1590.0
51.0
54.0
8.5
105.0
7400.0
450.0
8600.0
180.0
670.0
151.0
81.0
47200.0
157500.0
20700.0
300.0
260.0
160.0
4900.0
670.0
363.0
345.0
467.0
824.0
74.0
110.0
320.0
190.0
1000.0
410.0
30.0
320.0
130.0
4300.0
8800.0
6000.0
5300.0
6100.0
5600.0
8500.0
4100.0
5800.0
7000.0
7100.0
2000.0
44100.0
15900.0
3400.0
4600.0
6900.0
260.0
27600.0
1550.0
1820.0
2500.0
9350.0
15750.0
21390.0
670.0
53.0
40.0
180.0
2390.0
670.0
50600.0
2000.0
1000.0
7200.0
6700.0
13900.0
4800.0
5300.0
35200.0
33500.0
800.0
24300.0
980.0
1600.0
3800.0
5160.0
670.0
670.0
670.0
24100.0
11410.0
124930.0
670.0
1820.0
15750.0
9350.0
21390.0
1550.0
940.0
280.0
7280.0
9120.0
180.0
670.0
7.6
7.6
9.2
17.2
17.4
19.7
30.0
34.7
36.2
69.1
93.5
153.1
195.6
298.8
375.0
378.2
525.9
748.5
12.4
13.0
13.2
13.3
14.5
15.2
16.5
18.5
19.0
37.2
43.3
50.8
52.1
453.0
40.0
53.0
200.0
230.0
410.0
450.0
30.0
650.0
151.0
81.0
74.0
130.0
150.0
240.0
260.0
330.0
350.0
410.0
520.0
650.0
110.0
130.0
170.0
230.0
330.0
360.0
380.0
390.0
410.0
410.0
480.0
490.0
630.0
660.0
730.0
780.0
910.0
450.0
970.0
260.0
300.0
600.0
940.0
2430.0
2510.0
37840.0
197730.0
6490.0
2370.0
53.0
40.0
7600.0
670.0
670.0
400.0
190.0
680.0
72.0
320.0
8.1
670.0
40.0
15.2
0.2
8.1
3.1
46280.0
46290.0
249990.0
102440.0
60520.0
54560.0
62030.0
90480.0
46870.0
6710.0
14260.0
66920.0
79620.0
35220.0
39320.0
66960.0
21240.0
19660.0
19640.0
96930.0
76790.0
19370.0
5270.0
6470.0
14740.0
7480.0
14150.0
16510.0
220.0
9190.0
2500.0
17200.0
18200.0
4300.0
500.0
4300.0
2500.0
4890.0
2200.0
28100.0
63.0
500.0
65.0
50.0
60.0
2700.0
53000.0
70000.0
28000.0
64000.0
3400.0
600.0
2900.0
57000.0
1500.0
200.0
28000.0
75000.0
6100.0
13000.0
4100.0
7500.0
7500.0
42790.0
36.82
41.65
54.64
22.83
18.06
22.42
8060.0
460.0
3220.0
1640.0
4700.0
6380.0
160.0
140.0
11900.0
890.0
2800.0
160.0
3000.0
4700.0
11000.0
7100.0
230.0
900.0
53.0
34.0
19.0
15.2
17.2
135.0
551.0
165.0
47.0
356.0
43.0
14.0
34.0
104.0
50.0
77.0
900.0
600.0
2214.0
1849.0
478.0
4601.0
2899.0
1057.0
3333.0
322.0
2641.0
524.0
3961.0
33.0
1.113
4.117
33.22
0.066
27.58
4.094
0.852
0.039
6.073
12.83
13.95
3.496
165.21
70.0
90.0
210.0
450.0
490.0
200.0
310.0
330.0
350.0
190.0
200.0
140.0
130.0
170.0
270.0
150.0
170.0
320.0
310.0
300.0
310.0
310.0
240.0
460.0
340.0
170.0
170.0
190.0
210.0
300.0
280.0
220.0
230.0
200.0
120.0
290.0
320.0
380.0
410.0
190.0
53.0
770.0
440.0
1120.0
530.0
300.0
364.0
287.0
459.0
528.0
233.0
490.0
322.0
417.0
356.0
268.0
550.0
339.0
53.0
670.0
2500.0
72.0
47200.0
157000.0
12.02
26.92
177.83
21.38
21.0
23.0
22.39
178.0
34673.69
35000.0
12.0
27.0
1460.0
22400.0
9360.0
1360.0
20.0
1412.54
22387.21
9332.54
1348.96
22.91
4000.0
8.0
990.0
120.0
670.0
2500.0
9350.0
30.0
3900.0
1500.0
260.0
6810.0
9840.0
6500.0
11390.0
8600.0
96.0
13.0
1110.0
3450.0
3770.0
5400.0
5610.0
8640.0
9920.0
1740.0
2990.0
960.0
490.0
600.0
400.0
10600.0
200.0
150.0
80.0
390.0
5800.0
1200.0
1240.0
2860.0
5600.0
2070.0
180.0
2390.0
670.0
70.0
110.0
8.0
27.0
2770.0
4080.0
180.0
200.0
80.0
30.0
180.0
70.0
2350.0
2080.0
11.0
3.0
50.0
40.0
30.0
3880.0
140.0
180.0
7.0
15.0
10760.0
1570.0
1550.0
250.0
750.0
430.0
80.0
700.0
600.0
500.0
4100.0
420.0
410.0
45.0
10960.0
6100.0
1550.0
1810.0
400.0
1443.0
5132.0
12760.0
435.0
6960.0
7706.0
554.0
8017.0
9797.0
365.0
2277.0
1867.0
1481.0
10530.0
1798.0
10588.0
11169.0
7635.0
8423.0
18285.0
1130.0
1541.0
2716.0
1372.0
966.0
15190.0
3565.0
5485.0
539.0
1370.0
4943.0
4086.0
385.0
970.0
2874.0
327.0
174.0
210.0
390.0
124.0
1365.0
949.0
290.0
124.0
274.0
83.0
205.0
236.0
271.0
207.0
117.0
1476.0
212.0
390.0
477.0
1005.0
290.0
386.0
692.0
107.0
239.0
100.0
284.0
131.0
502.0
466.0
14.8
76.3
16.1
81.1
28.8
24.0
34.7
36.5
35.4
34.5
33.7
34.8
60.1
160.0
22.0
23.4
28.1
101.0
55.0
20000.0
50000.0
6000.0
15000.0
14000.0
27000.0
25000.0
19000.0
2200.0
12000.0
31000.0
59000.0
60000.0
341000.0
62000.0
78000.0
127000.0
170000.0
3500.0
8000.0
12000.0
25000.0
11000.0
39000.0
32000.0
7000.0
4600.0
4700.0
15600.0
2200.0
7300.0
2040.0
900.0
900.0
23300.0
27400.0
52400.0
49000.0
38400.0
278.0
1.81
982.0
81.0
28.0
34.0
45.0
62.0
61.0
50.0
52.0
71.0
77.0
77.0
193.0
39980.0
143.0
323.0
124.0
136.0
165.0
118.0
373.0
582.0
462.0
252.0
78.0
409.0
302.0
206.0
191.0
655.0
448.0
2520.0
71890.0
880.0
2050.0
670.0
620.0
440.0
7197.0
7211.07
1350.0
21200.0
51.0
14400.0
6210.0
260.0
0.22
0.7
6.23
0.47
0.24
4196.0
20290.0
2.5
5.0
3350.0
5.3
53.0
29.0
74.0
53.0
56.0
110.0
98.0
400.0
560.0
510.0
25.0
25.0
30.0
22.0
49.0
990.0
39.0
25.0
41.0
2200.0
3600.0
1500.0
6000.0
1400.0
55.0
28.0
40.0
42.0
100.0
103.0
30.0
24380.0
23320.0
13340.0
9570.0
9120.0
5260.0
4520.0
3940.0
4520.0
5680.0
3730.0
9550.0
11500.0
10970.0
9060.0
7320.0
5150.0
3630.0
3360.0
3350.0
4450.0
4150.0
3310.0
6210.0
5110.0
3690.0
2550.0
2480.0
1920.0
1590.0
1670.0
2350.0
2050.0
2030.0
1020.0
4090.0
180.0
1840.0
6500.0
4400.0
35000.0
29000.0
39000.0
22000.0
2500.0
12000.0
290.0
500.0
330.0
340.0
16000.0
300.0
760.0
63.0
170.0
16.0
8.0
88.0
55.0
100.0
1590.0
280.0
44.0
28.0
9990.0
43.0
21.0
17.0
16.0
13.0
12.0
9.0
6.0
12.0
120.0
9000.0
360.0
19.0
4000.0
3408.0
2850.0
2180.0
573.0
468.0
383.0
187.0
130.0
274.0
62.0
17.3
9.5
25.6
2.8
1.2
3.5
2.1
2.07
1.3
0.72
40800.0
45700.0
6.0
6.0
6.0
7.0
6.0
7.0
270.0
250.0
210.0
320.0
350.0
210.0
170.0
440.0
400.0
90.0
9500.0
1300.0
400.0
1800.0
200.0
220.0
190.0
430.0
400.0
410.0
350.0
480.0
9600.0
5500.0
13.0
11.0
14.0
10.0
3270.0
7400.0
3680.0
44800.0
350.0
1020.0
30.0
15750.0
6100.0
16100.0
1100.0
4600.0
100.0
10.0
900.0
920.0
1000.0
480.0
35200.0
15500.0
6300.0
1300.0
15900.0
13300.0
13200.0
45000.0
163000.0
90000.0
134000.0
178000.0
201000.0
279000.0
181000.0
192000.0
7.4
6.5
7.7
7.4
7.0
5.0
41999.0
43056.0
121872.0
22960.0
13647.0
1022.0
1058.0
650.0
440.0
535.0
555.0
628.0
598.0
632.0
644.0
653.0
470.0
653.0
462.0
430.0
474.0
540.0
498.0
599.0
592.0
3430.0
44290.0
25257.0
37984.0
35766.0
58909.0
78355.0
61559.0
28285.0
66421.0
2270.0
68052.0
15162.0
11179.0
14906.0
30658.0
15016.0
97513.0
96596.0
35261.0
78425.0
74635.0
14186.0
12023.0
46460.0
46659.0
7859.0
6043.0
85214.0
96966.0
73741.0
86018.0
32486.0
24495.0
70879.0
76080.0
20662.0
21768.0
24841.0
20790.0
19483.0
21811.0
2730.0
2949.0
20196.0
24610.0
2066.0
2122.0
33219.0
34497.0
38017.0
40823.0
24672.0
24194.0
2589.0
3177.0
36636.0
33224.0
70212.0
81723.0
29582.0
31235.0
20566.0
20218.0
27379.0
29017.0
6825.0
7542.0
10309.0
9531.0
65277.0
71328.0
41212.0
38323.0
52149.0
62896.0
87945.0
92786.0
49309.0
60336.0
3474.0
3775.0
10641.0
12377.0
75220.0
99007.0
39188.0
40323.0
7569.0
7266.0
14566.0
18188.0
2784.0
3037.0
6387.0
6247.0
4201.0
4194.0
35815.0
41309.0
44506.0
43915.0
25018.0
27477.0
13886.0
15471.0
8187.0
8223.0
58260.0
59922.0
80286.0
93874.0
1921.0
2115.0
6357.0
8208.0
9045.0
8763.0
19870.0
20025.0
17695.0
19859.0
7291.0
8332.0
11265.0
13102.0
63771.0
49305.0
14513.0
14574.0
3778.0
4547.0
12088.0
10023.0
6574.0
5475.0
12220.0
10103.0
8537.0
10045.0
9410.0
7953.0
28881.0
34595.0
5196.0
6522.0
15952.0
22754.0
16299.0
21720.0
50132.0
58401.0
27312.0
32468.0
77115.0
68167.0
1809.0
1882.0
9067.0
13392.0
95327.0
25708.0
39932.0
55365.0
64688.0
1286.0
1165.0
989.0
54100.0
51166.0
38113.0
57461.0
37806.0
50419.0
38643.0
39459.0
25792.0
20661.0
522.0
522.0
436.0
66287.0
25682.0
1226.0
1059.0
1017.0
900.0
2968.0
3933.0
3174.0
383.0
361.0
2230.0
2253.0
46186.0
37198.0
29899.0
992.0
1005.0
83162.0
77592.0
5822.0
5927.0
2248.0
2443.0
700.0
722.0
34030.0
76435.0
72299.0
2278.0
1853.0
7830.0
6577.0
18677.0
17369.0
27831.0
31700.0
27170.0
24164.0
74645.0
71425.0
15356.0
16798.0
149.0
133.0
25299.0
25967.0
7157.0
7384.0
45705.0
44654.0
801.0
610.0
4555.0
4966.0
80690.0
94364.0
3007.0
2637.0
1841.0
1654.0
450.0
366.0
15261.0
14959.0
10072.0
11792.0
66031.0
20926.0
20592.0
72165.0
72010.0
34091.0
33797.0
4357.0
3816.0
7923.0
7709.0
786.0
865.0
79412.0
83634.0
728.0
692.0
5312.0
6501.0
1953.0
1966.0
3428.0
3072.0
68.0
74.0
92316.0
91831.0
396.0
378.0
2963.0
453.0
466.0
3114.0
3488.0
280.0
305.0
808.0
532.0
2570.0
2598.0
90037.0
93525.0
247.0
258.0
1523.0
1637.0
17769.0
22124.0
2524.0
2511.0
50867.0
55872.0
485.0
517.0
3453.0
3981.0
19314.0
18172.0
1844.0
2019.0
1072.0
1062.0
44431.0
50603.0
274.0
319.0
309.0
332.0
253.0
315.0
21897.0
18851.0
479.0
585.0
1186.0
1777.0
2676.0
2708.0
857.0
800.0
394.0
449.0
5810.0
7131.0
19155.0
16269.0
903.0
891.0
16730.0
18480.0
626.0
652.0
421.0
563.0
2985.0
3583.0
1858.0
1954.0
2093.0
2218.0
16109.0
14284.0
5769.0
7415.0
1066.0
1023.0
804.0
853.0
27578.0
34219.0
2562.0
3089.0
1079.0
1228.0
4224.0
3905.0
2151.0
2537.0
1507.0
1447.0
972.0
1024.0
423.0
473.0
1318.0
1530.0
5136.0
5848.0
2272.0
2616.0
2010.0
2065.0
905.0
1062.0
871.0
843.0
2506.0
2580.0
16591.0
17219.0
2974.0
3241.0
3841.0
3916.0
5595.0
8760.0
1789.0
1905.0
20454.0
19662.0
1136.0
1382.0
9528.0
10248.0
281.0
383.0
3279.0
3758.0
2794.0
1625.0
1634.0
1809.0
1074.0
1242.0
1851.0
2130.0
2709.0
2666.0
43948.0
39730.0
5160.0
4513.0
1190.0
1186.0
67731.0
67368.0
1299.0
1505.0
3018.0
2938.0
6200.0
6096.0
639.0
701.0
1697.0
2132.0
713.0
737.0
4972.0
4995.0
243.0
259.0
27372.0
25976.0
421.0
446.0
674.0
711.0
746.0
819.0
5342.0
4546.0
164.0
143.0
2691.0
2896.0
676.0
868.0
1187.0
961.0
10123.0
8667.0
213.0
206.0
330.0
341.0
3732.0
3000.0
2612.0
2710.0
282.0
269.0
411.0
493.0
469.0
6782.0
8836.0
8767.0
1173.0
1518.0
1404.0
892.0
1421.0
1290.0
699.0
883.0
832.0
538.0
616.0
618.0
757.0
962.0
864.0
998.0
1231.0
1124.0
416.0
475.0
383.0
2187.0
2452.0
2619.0
9282.0
10723.0
10116.0
8537.0
8993.0
9514.0
3252.0
3449.0
3569.0
40556.0
37565.0
26445.0
28876.0
1155.0
1347.0
1403.0
250.0
302.0
355.0
422.0
498.0
497.0
3485.0
5543.0
5190.0
3497.0
4099.0
4030.0
203.0
230.0
270.0
1043.0
1382.0
1310.0
8696.0
13554.0
17040.0
6078.0
306.0
31732.0
163.0
128.0
46.0
242.0
260.0
82.0
1118.0
326.0
25.0
2569.0
1197.0
1780.0
894.0
435.0
440.0
316.0
338.0
701.0
439.0
411.0
374.0
353.0
440.0
447.0
847.0
925.0
461.0
794.0
731.0
432.0
353.0
1102.0
317.0
406.0
649.0
516.0
384.0
402.0
374.0
289.0
506.0
262.0
224.0
632.0
28921.0
743.0
1537.0
20064.0
39.0
55.0
11659.0
11537.0
7292.0
11278.0
93.0
138.0
803.0
194.0
512.0
55738.0
36.0
54.0
39.0
54.0
27268.0
9976.0
17943.0
1251.0
1744.0
52.0
78.0
1014.0
1335.0
1357.0
1928.0
580.0
1147.0
1361.0
2016.0
2841.0
4417.0
72555.0
837.0
1336.0
639.0
1758.0
3681.0
7822.0
1361.0
3404.0
1146.0
2572.0
1098.0
2064.0
2943.0
5873.0
793.0
2001.0
954.0
1914.0
2104.0
4225.0
1970.0
5692.0
1295.0
2346.0
1094.0
2636.0
47158.0
10735.0
19669.0
1445.0
3272.0
43542.0
56.0
100.0
9980.0
22962.0
1322.0
1273.0
939.0
815.0
17844.0
13947.0
19303.0
19051.0
30827.0
40.0
29.0
283.0
156.0
312.0
59.0
7237.0
5891.0
678.0
611.0
35.0
19.0
30.0
792.0
829.0
629.0
543.0
866.0
790.0
695.0
623.0
1291.0
947.0
1391.0
1234.0
4420.0
4281.0
1597.0
1617.0
955.0
1044.0
633.0
594.0
25.0
41.0
414.0
502.0
96417.0
4146.0
16597.0
6894.0
19858.0
5756.0
17018.0
1687.0
3911.0
238.0
901.0
802.0
2138.0
3623.0
2350.0
313.0
187.0
20892.0
17698.0
1273.0
967.0
27708.0
23521.0
124.0
117.0
95.0
197.0
6222.0
4918.0
20457.0
17610.0
18.0
15.0
13.0
22250.0
4957.0
2327.0
3077.0
2416.0
120.0
110.0
246.0
23342.0
14094.0
10734.0
64.0
54.0
203.0
213.0
224.0
2242.0
1913.0
6453.0
5614.0
22.0
19.0
19.0
289.0
396.0
533.0
101.0
95.0
86868.0
18.0
16.0
15.0
204.0
197.0
288.0
50828.0
1865.0
1937.0
71.0
57.0
3156.0
2858.0
3789.0
65.0
66.0
479.0
316.0
72.0
454.0
100.0
85.0
409.0
455.0
145.0
150.0
604.0
628.0
28794.0
37604.0
28409.0
123.0
95.0
5363.0
961.0
1340.0
1077.0
163.0
154.0
30.0
30.0
133.0
191.0
235.0
24584.0
65.0
70.0
70.0
108.0
3902.0
6457.0
4275.0
4353.0
5376.0
4136.0
107.0
171.0
117.0
21.0
16.0
31.0
15.0
23.0
23.0
25.0
31.0
7011.0
4478.0
395.0
261.0
1065.0
574.0
28.0
14.0
32.0
13.0
28.0
28.0
24.0
36.0
12.0
11.0
322.0
241.0
288.0
36799.0
11620.0
743.0
68.0
134.0
33.0
64.0
52.0
90.0
50.0
73.0
181.0
39.0
79.0
57.0
143.0
1276.0
9145.0
19.0
34.0
17.0
29.0
34.0
27.0
35.0
15.0
328.0
264.0
122.0
75560.0
3145.0
54.0
107.0
14.0
26.0
10.0
20.0
22.0
27.0
29.0
1788.0
6735.0
24.0
48.0
38.0
52.0
35.0
60.0
47900.0
20.0
34.0
19.0
33.0
53.0
32.0
42.0
176.0
208.0
189.0
992.0
1166.0
100.0
90.0
156.0
241.0
3053.0
1673.0
50.0
46.0
40.0
48.0
78.0
242.0
334.0
360.0
114.0
63.0
52.0
85.0
58.0
60.0
85.0
62.0
106.0
94.0
68.0
116.0
478.0
308.0
538.0
82.0
114.0
244.0
49.0
54.0
94.0
60.0
69.0
414.0
419.0
74.0
63.0
112.0
1115.0
784.0
5557.0
4255.0
30.0
26.0
45.0
29.0
33.0
1560.0
770.0
2937.0
1557.0
30131.0
258.0
186.0
325.0
93.0
73.0
126.0
241.0
131.0
349.0
297.0
189.0
345.0
456.0
272.0
503.0
51.0
43.0
65.0
46.0
52.0
203.0
120.0
206.0
1791.0
46826.0
287.0
614.0
235.0
395.0
26454.0
38426.0
43824.0
29.0
38.0
37.0
43.0
51.0
47457.0
62908.0
59840.0
67353.0
1548.0
1442.0
3682.0
2567.0
794.0
1336.0
1899.0
1795.0
2849.0
982.0
24631.0
2245.0
110.0
57.0
6049.0
119.0
349.0
319.0
2343.0
1490.0
1614.0
9731.0
8119.0
1030.0
622.0
340.0
336.0
52128.0
10833.0
12.0
971.0
85.0
22793.0
10833.0
20.0
10.0
375.0
67.0
18970.0
1621.0
58.0
100600.0
113800.0
22700.0
35100.0
10700.0
70900.0
11200.0
11100.0
176500.0
59200.0
14400.0
10400.0
1700.0
7500.0
7600.0
96500.0
2100.0
200.0
200.0
100.0
100.0
1300.0
50200.0
200.0
4000.0
4200.0
11700.0
1800.0
600.0
900.0
31400.0
2100.0
20800.0
7700.0
4300.0

### **Iterate the *molecule_chembl_id* to a list**

In [53]:
mol_cid = []
for i in df2.molecule_chembl_id:
  print(i)
  mol_cid.append(i)

CHEMBL480
CHEMBL178459
CHEMBL3545157
CHEMBL297453
CHEMBL4303595
CHEMBL444186
CHEMBL55400
CHEMBL1886408
CHEMBL505670
CHEMBL460499
CHEMBL1271993
CHEMBL3665060
CHEMBL1096979
CHEMBL164
CHEMBL1422849
CHEMBL284861
CHEMBL286080
CHEMBL3963349
CHEMBL480
CHEMBL3797437
CHEMBL289356
CHEMBL1725120
CHEMBL1356238
CHEMBL105712
CHEMBL508112
CHEMBL243652
CHEMBL259018
CHEMBL449298
CHEMBL566136
CHEMBL1608472
CHEMBL60718
CHEMBL1917204
CHEMBL226652
CHEMBL119171
CHEMBL66953
CHEMBL4303154
CHEMBL4303503
CHEMBL4303702
CHEMBL2368547
CHEMBL1200930
CHEMBL1475252
CHEMBL271023
CHEMBL406050
CHEMBL1255778
CHEMBL1201236
CHEMBL388676
CHEMBL52
CHEMBL505308
CHEMBL1697725
CHEMBL4303376
CHEMBL28
CHEMBL3348861
CHEMBL1917204
CHEMBL488755
CHEMBL1256915
CHEMBL3545085
CHEMBL403183
CHEMBL1200471
CHEMBL3747259
CHEMBL324842
CHEMBL3833381
CHEMBL1380480
CHEMBL1161936
CHEMBL120563
CHEMBL51085
CHEMBL1188627
CHEMBL4303331
CHEMBL1256832
CHEMBL510038
CHEMBL964
CHEMBL1474701
CHEMBL1408862
CHEMBL929
CHEMBL4303595
CHEMBL444478
CHEMBL571700
CHEMBL472940
CHEMBL1374426
CHEMBL518800
CHEMBL596674
CHEMBL164
CHEMBL270299
CHEMBL4303312
CHEMBL188434
CHEMBL4303618
CHEMBL128251
CHEMBL4303361
CHEMBL4303622
CHEMBL111654
CHEMBL297453
CHEMBL508338
CHEMBL9116
CHEMBL1591074
CHEMBL329522
CHEMBL465704
CHEMBL2107818
CHEMBL11359
CHEMBL8260
CHEMBL2354521
CHEMBL508280
CHEMBL1333953
CHEMBL3187985
CHEMBL477197
CHEMBL1271993
CHEMBL1449651
CHEMBL3545157
CHEMBL178459
CHEMBL1201073
CHEMBL376488
CHEMBL154580
CHEMBL354349
CHEMBL1382627
CHEMBL4303664
CHEMBL5219995
CHEMBL2316746
CHEMBL213543
CHEMBL4796938
CHEMBL4764751
CHEMBL4857345
CHEMBL4850298
CHEMBL3559293
CHEMBL4777223
CHEMBL4852855
CHEMBL4796938
CHEMBL4764751
CHEMBL4796938
CHEMBL3559293
CHEMBL4868590
CHEMBL92708
CHEMBL3559293
CHEMBL4518490
CHEMBL64925
CHEMBL92708
CHEMBL231813
CHEMBL4875501
CHEMBL4877358
CHEMBL4869416
CHEMBL4869416
CHEMBL4877358
CHEMBL4848534
CHEMBL4864930
CHEMBL4850314
CHEMBL4851261
CHEMBL4860368
CHEMBL4854844
CHEMBL4863973
CHEMBL4855167
CHEMBL4852069
CHEMBL4877143
CHEMBL4857654
CHEMBL4870400
CHEMBL4854494
CHEMBL4874978
CHEMBL4852238
CHEMBL4846173
CHEMBL4875555
CHEMBL4863334
CHEMBL4065616
CHEMBL4865625
CHEMBL4854368
CHEMBL4874748
CHEMBL4870398
CHEMBL4878063
CHEMBL4065616
CHEMBL4845924
CHEMBL4869436
CHEMBL4857861
CHEMBL4870398
CHEMBL4878063
CHEMBL4065616
CHEMBL4845924
CHEMBL4869436
CHEMBL4857861
CHEMBL5179067
CHEMBL5207860
CHEMBL5208812
CHEMBL5179067
CHEMBL5207860
CHEMBL5208812
CHEMBL18786
CHEMBL460499
CHEMBL51085
CHEMBL9470
CHEMBL964
CHEMBL406050
CHEMBL3545157
CHEMBL8260
CHEMBL8260
CHEMBL485818
CHEMBL218394
CHEMBL3427166
CHEMBL5180554
CHEMBL5196922
CHEMBL5207860
CHEMBL5179067
CHEMBL5208812
CHEMBL5184946
CHEMBL5187773
CHEMBL1255891
CHEMBL64925
CHEMBL92708
CHEMBL304784
CHEMBL4518490
CHEMBL18786
CHEMBL460499
CHEMBL51085
CHEMBL9470
CHEMBL964
CHEMBL406050
CHEMBL3545157
CHEMBL485818
CHEMBL218394
CHEMBL3427166
CHEMBL5180554
CHEMBL5196922
CHEMBL5207860
CHEMBL5179067
CHEMBL5208812
CHEMBL5184946
CHEMBL5187773
CHEMBL1255891
CHEMBL64925
CHEMBL92708
CHEMBL304784
CHEMBL4518490
CHEMBL5196922
CHEMBL5180554
CHEMBL3427166
CHEMBL218394
CHEMBL8260
CHEMBL485818
CHEMBL5187773
CHEMBL5184946
CHEMBL5201546
CHEMBL5171214
CHEMBL562121
CHEMBL1173049
CHEMBL445978
CHEMBL395990
CHEMBL611029
CHEMBL187460
CHEMBL464274
CHEMBL186141
CHEMBL3427166
CHEMBL4802135
CHEMBL4777223
CHEMBL5208946
CHEMBL5174111
CHEMBL5183847
CHEMBL5082224
CHEMBL5188908
CHEMBL5188502
CHEMBL5201620
CHEMBL5172248
CHEMBL5180494
CHEMBL5192350
CHEMBL5204987
CHEMBL5181886
CHEMBL5188982
CHEMBL5082224
CHEMBL5180524
CHEMBL5200851
CHEMBL5173559
CHEMBL3605457
CHEMBL549695
CHEMBL5077800
CHEMBL5071508
CHEMBL5179681
CHEMBL5183676
CHEMBL5185454
CHEMBL5183892
CHEMBL5199419
CHEMBL5171009
CHEMBL5201060
CHEMBL5173688
CHEMBL5179021
CHEMBL5085659
CHEMBL5175433
CHEMBL5085054
CHEMBL5207904
CHEMBL5079592
CHEMBL5208693
CHEMBL5093083
CHEMBL5072144
CHEMBL5073830
CHEMBL5180299
CHEMBL5182901
CHEMBL5177666
CHEMBL5172181
CHEMBL5197139
CHEMBL5172897
CHEMBL5171621
CHEMBL5175380
CHEMBL5175329
CHEMBL5170174
CHEMBL5187526
CHEMBL5199721
CHEMBL5180056
CHEMBL5200289
CHEMBL5174096
CHEMBL5183725
CHEMBL5174607
CHEMBL5207076
CHEMBL5182315
CHEMBL5200707
CHEMBL5205511
CHEMBL5176085
CHEMBL5184650
CHEMBL5174085
CHEMBL5173886
CHEMBL549695
CHEMBL3233815
CHEMBL3233809
CHEMBL3233822
CHEMBL5192637
CHEMBL5171052
CHEMBL5175589
CHEMBL5180567
CHEMBL5187162
CHEMBL5191209
CHEMBL549695
CHEMBL3233815
CHEMBL3233809
CHEMBL3233822
CHEMBL5192637
CHEMBL5171052
CHEMBL5175589
CHEMBL5180567
CHEMBL5187162
CHEMBL5191209
CHEMBL5075209
CHEMBL5198567
CHEMBL5198567
CHEMBL5198073
CHEMBL5179778
CHEMBL5190754
CHEMBL5179611
CHEMBL5195394
CHEMBL5197241
CHEMBL5172924
CHEMBL4777223
CHEMBL4802135
CHEMBL5194970
CHEMBL5177181
CHEMBL5170254
CHEMBL5184754
CHEMBL5194113
CHEMBL5191524
CHEMBL5182801
CHEMBL5186585
CHEMBL5179857
CHEMBL5205104
CHEMBL5196969
CHEMBL5202324
CHEMBL5179950
CHEMBL5172920
CHEMBL5202164
CHEMBL5189428
CHEMBL5201497
CHEMBL5205913
CHEMBL5194970
CHEMBL218394
CHEMBL5171142
CHEMBL5202866
CHEMBL5178875
CHEMBL5205477
CHEMBL5189578
CHEMBL5190267
CHEMBL5176166
CHEMBL5203715
CHEMBL5178556
CHEMBL5185670
CHEMBL5169820
CHEMBL5204033
CHEMBL5199403
CHEMBL5208464
CHEMBL5193629
CHEMBL5173899
CHEMBL5177381
CHEMBL5203726
CHEMBL5201264
CHEMBL5205992
CHEMBL5171771
CHEMBL5183770
CHEMBL5202077
CHEMBL5178763
CHEMBL5203900
CHEMBL4852855
CHEMBL5202866
CHEMBL5202866
CHEMBL5196043
CHEMBL5180793
CHEMBL5175509
CHEMBL5203173
CHEMBL5203431
CHEMBL5179663
CHEMBL5170923
CHEMBL5200532
CHEMBL5197166
CHEMBL5206924
CHEMBL5182608
CHEMBL5206180
CHEMBL5204666
CHEMBL5184261
CHEMBL5187437
CHEMBL5183731
CHEMBL5207867
CHEMBL5176816
CHEMBL5176204
CHEMBL4802135
CHEMBL218394
CHEMBL218394
CHEMBL5205883
CHEMBL5198559
CHEMBL5199388
CHEMBL5181062
CHEMBL5200317
CHEMBL218394
CHEMBL468553
CHEMBL5187156
CHEMBL5188282
CHEMBL5189793
CHEMBL5186663
CHEMBL5196901
CHEMBL5207375
CHEMBL5183847
CHEMBL5208498
CHEMBL5194350
CHEMBL5201925
CHEMBL5188818
CHEMBL5207127
CHEMBL5185732
CHEMBL5206128
CHEMBL5192777
CHEMBL5203920
CHEMBL5177083
CHEMBL5197155
CHEMBL5187177
CHEMBL5195764
CHEMBL5200024
CHEMBL5196584
CHEMBL5188525
CHEMBL5192363
CHEMBL5203047
CHEMBL5208006
CHEMBL3427166
CHEMBL5185160
CHEMBL5180730
CHEMBL4851462
CHEMBL5195798
CHEMBL5189649
CHEMBL5190756
CHEMBL5204224
CHEMBL5208639
CHEMBL5170425
CHEMBL4777223
CHEMBL2316337
CHEMBL5174083
CHEMBL5174083
CHEMBL3545157
CHEMBL50894
CHEMBL296586
CHEMBL5173280
CHEMBL5171650
CHEMBL8260
CHEMBL5173280
CHEMBL5171650
CHEMBL4175014
CHEMBL5181347
CHEMBL1595621
CHEMBL5174530
CHEMBL5184792
CHEMBL5193596
CHEMBL5176036
CHEMBL5173143
CHEMBL5184210
CHEMBL5189591
CHEMBL5182294
CHEMBL5180774
CHEMBL5169690
CHEMBL5179702
CHEMBL5182106
CHEMBL5205478
CHEMBL5198234
CHEMBL5208244
CHEMBL5186059
CHEMBL5204130
CHEMBL5184334
CHEMBL5189565
CHEMBL5173920
CHEMBL5188939
CHEMBL5199191
CHEMBL5199531
CHEMBL5204452
CHEMBL5204064
CHEMBL5207613
CHEMBL5202104
CHEMBL5189863
CHEMBL5174547
CHEMBL4855437
CHEMBL5207392
CHEMBL5192027
CHEMBL5191017
CHEMBL5169323
CHEMBL5207081
CHEMBL5192248
CHEMBL5177782
CHEMBL5169680
CHEMBL5204680
CHEMBL5186338
CHEMBL5208709
CHEMBL5184362
CHEMBL5178465
CHEMBL5192654
CHEMBL5186708
CHEMBL5194755
CHEMBL5181137
CHEMBL5178568
CHEMBL5197891
CHEMBL490820
CHEMBL5205750
CHEMBL472940
CHEMBL5190583
CHEMBL121556
CHEMBL4441971
CHEMBL5075209
CHEMBL5208720
CHEMBL5075209
CHEMBL5207119
CHEMBL4764751
CHEMBL3427166
CHEMBL8260
CHEMBL485818
CHEMBL8260
CHEMBL8260
CHEMBL51085
CHEMBL51085
CHEMBL5172346
CHEMBL5176411
CHEMBL51085
CHEMBL3922662
CHEMBL3983492
CHEMBL3928799
CHEMBL3912164
CHEMBL549695
CHEMBL3427166
CHEMBL549695
CHEMBL549695
CHEMBL187460
CHEMBL227075
CHEMBL187266
CHEMBL599894
CHEMBL1397270
CHEMBL290904
CHEMBL15192
CHEMBL5191209
CHEMBL3233809
CHEMBL5174096
CHEMBL5206079
CHEMBL5173886
CHEMBL5182315
CHEMBL549695
CHEMBL5197139
CHEMBL5172181
CHEMBL5172897
CHEMBL5177666
CHEMBL5201129
CHEMBL549695
CHEMBL551592
CHEMBL486027
CHEMBL53566
CHEMBL14193
CHEMBL55400
CHEMBL55400
CHEMBL727
CHEMBL727
CHEMBL727
CHEMBL727
CHEMBL3407552
CHEMBL2105734
CHEMBL187460
CHEMBL363535
CHEMBL1473252
CHEMBL1200596
CHEMBL454129
CHEMBL5188555
CHEMBL5206451
CHEMBL5206451
CHEMBL2103763
CHEMBL3617994
CHEMBL2103763
CHEMBL3617994
CHEMBL5204399
CHEMBL5182468
CHEMBL5196343
CHEMBL5196473
CHEMBL5208536
CHEMBL51085
CHEMBL3922662
CHEMBL3983492
CHEMBL3928799
CHEMBL3912164
CHEMBL5194538
CHEMBL5199343
CHEMBL5195364
CHEMBL5206009
CHEMBL5193976
CHEMBL5177233
CHEMBL5202141
CHEMBL5194538
CHEMBL5199343
CHEMBL5195364
CHEMBL5206009
CHEMBL5193976
CHEMBL5177233
CHEMBL5202141
CHEMBL964
CHEMBL4764751
CHEMBL5180964
CHEMBL5195478
CHEMBL5200040
CHEMBL5207566
CHEMBL5203574
CHEMBL5205787
CHEMBL3885329
CHEMBL5199094
CHEMBL5174138
CHEMBL5203407
CHEMBL3884779
CHEMBL5182830
CHEMBL5186446
CHEMBL5207769
CHEMBL5173857
CHEMBL5172144
CHEMBL5190907
CHEMBL5183017
CHEMBL5176330
CHEMBL5189974
CHEMBL5179730
CHEMBL5207843
CHEMBL5189874
CHEMBL5201697
CHEMBL5197113
CHEMBL5198279
CHEMBL5169416
CHEMBL5192541
CHEMBL5182229
CHEMBL5191197
CHEMBL5191663
CHEMBL5179310
CHEMBL5175884
CHEMBL5199219
CHEMBL5185152
CHEMBL5206326
CHEMBL5179883
CHEMBL5197105
CHEMBL5189683
CHEMBL5192273
CHEMBL5182755
CHEMBL5173399
CHEMBL1997422
CHEMBL3545157
CHEMBL5199064
CHEMBL5170994
CHEMBL5175377
CHEMBL1992382
CHEMBL1994837
CHEMBL5206721
CHEMBL5186313
CHEMBL5203288
CHEMBL5203660
CHEMBL5193704
CHEMBL5187551
CHEMBL5180925
CHEMBL5195265
CHEMBL5180049
CHEMBL5198323
CHEMBL5181942
CHEMBL5198114
CHEMBL1965444
CHEMBL5181310
CHEMBL5174417
CHEMBL5195352
CHEMBL5187397
CHEMBL5172901
CHEMBL5174488
CHEMBL5171994
CHEMBL5202218
CHEMBL5171422
CHEMBL5197257
CHEMBL5195352
CHEMBL5195352
CHEMBL5195352
CHEMBL51085
CHEMBL5196018
CHEMBL4796938
CHEMBL218394
CHEMBL3427166
CHEMBL5195325
CHEMBL8260
CHEMBL1908391
CHEMBL4802135
CHEMBL5173582
CHEMBL5182995
CHEMBL5173858
CHEMBL5183165
CHEMBL5174632
CHEMBL5185801
CHEMBL517080
CHEMBL516703
CHEMBL517080
CHEMBL5198897
CHEMBL1703831
CHEMBL5176190
CHEMBL5172482
CHEMBL5207227
CHEMBL5188739
CHEMBL5176486
CHEMBL5178149
CHEMBL5170578
CHEMBL5201817
CHEMBL5177648
CHEMBL5200414
CHEMBL5175672
CHEMBL5177146
CHEMBL5204604
CHEMBL5191265
CHEMBL1532997
CHEMBL5183334
CHEMBL5170392
CHEMBL5173090
CHEMBL5204705
CHEMBL5190812
CHEMBL5198660
CHEMBL5198161
CHEMBL1709906
CHEMBL5189273
CHEMBL5182841
CHEMBL5201634
CHEMBL5199130
CHEMBL5186395
CHEMBL5188666
CHEMBL5182008
CHEMBL5187129
CHEMBL5191848
CHEMBL5177329
CHEMBL5175153
CHEMBL5191706
CHEMBL5187806
CHEMBL5179454
CHEMBL1703831
CHEMBL5176190
CHEMBL5190812
CHEMBL4802135
CHEMBL33778
CHEMBL1241028
CHEMBL5172191
CHEMBL5187969
CHEMBL5171569
CHEMBL5172081
CHEMBL5190048
CHEMBL5172911
CHEMBL5193934
CHEMBL5178276
CHEMBL5198248
CHEMBL1214186
CHEMBL5171211
CHEMBL5184431
CHEMBL5184551
CHEMBL5188495
CHEMBL5170500
CHEMBL5075209
CHEMBL5190212
CHEMBL5206532
CHEMBL5180502
CHEMBL5193842
CHEMBL5174111
CHEMBL5082224
CHEMBL4802135
CHEMBL4777223
CHEMBL4796938
CHEMBL51085
CHEMBL5173274
CHEMBL3427166
CHEMBL2311694
CHEMBL5173559
CHEMBL5206685
CHEMBL5206685
CHEMBL4764751
CHEMBL51085
CHEMBL5188743
CHEMBL3983492
CHEMBL599894
CHEMBL549695
CHEMBL5197203
CHEMBL5206501
CHEMBL5207542
CHEMBL5178131
CHEMBL5169554
CHEMBL5186431
CHEMBL5201613
CHEMBL5172431
CHEMBL5189062
CHEMBL5208393
CHEMBL5179577
CHEMBL5204664
CHEMBL5175491
CHEMBL5198265
CHEMBL5195867
CHEMBL5180821
CHEMBL5196047
CHEMBL5193830
CHEMBL5182370
CHEMBL5176045
CHEMBL5193986
CHEMBL5170916
CHEMBL2311731
CHEMBL5190815
CHEMBL5188059
CHEMBL5171513
CHEMBL5170231
CHEMBL5179593
CHEMBL5171325
CHEMBL5171462
CHEMBL5188623
CHEMBL5192910
CHEMBL2311694
CHEMBL5176329
CHEMBL5179427
CHEMBL5170981
CHEMBL5195155
CHEMBL3427166
CHEMBL5179259
CHEMBL5194822
CHEMBL5198667
CHEMBL5206120
CHEMBL5190213
CHEMBL5193390
CHEMBL5191464
CHEMBL5191092
CHEMBL5187784
CHEMBL5190876
CHEMBL5192585
CHEMBL5191060
CHEMBL5173658
CHEMBL5171263
CHEMBL5195086
CHEMBL5195798
CHEMBL5182169
CHEMBL5189954
CHEMBL5200032
CHEMBL5200159
CHEMBL5206974
CHEMBL5187246
CHEMBL5203183
CHEMBL5175215
CHEMBL5200309
CHEMBL5205858
CHEMBL5185504
CHEMBL5199771
CHEMBL5204406
CHEMBL5186504
CHEMBL5203894
CHEMBL5193737
CHEMBL5174450
CHEMBL5208242
CHEMBL5191100
CHEMBL5209023
CHEMBL5207257
CHEMBL5170933
CHEMBL5206883
CHEMBL5208389
CHEMBL5175482
CHEMBL5177686
CHEMBL5176434
CHEMBL5170370
CHEMBL5179506
CHEMBL5191235
CHEMBL5183857
CHEMBL5204665
CHEMBL5189811
CHEMBL5172817
CHEMBL5198662
CHEMBL5205128
CHEMBL5209430
CHEMBL5195252
CHEMBL5192607
CHEMBL5209460
CHEMBL5181133
CHEMBL5175405
CHEMBL5177264
CHEMBL5171088
CHEMBL5177159
CHEMBL5201244
CHEMBL5194593
CHEMBL5203622
CHEMBL964
CHEMBL5206883
CHEMBL5175482
CHEMBL5176434
CHEMBL5204665
CHEMBL5189811
CHEMBL5198662
CHEMBL5192607
CHEMBL5181133
CHEMBL5175405
CHEMBL5177264
CHEMBL5201244
CHEMBL964
CHEMBL5184053
CHEMBL1479456
CHEMBL5205985
CHEMBL4802135
CHEMBL5183847
CHEMBL5200025
CHEMBL5206756
CHEMBL5208871
CHEMBL5199148
CHEMBL5178940
CHEMBL5172628
CHEMBL5195979
CHEMBL5186326
CHEMBL5180645
CHEMBL5174051
CHEMBL5206233
CHEMBL5180746
CHEMBL5194209
CHEMBL5174397
CHEMBL5180205
CHEMBL5188905
CHEMBL5188698
CHEMBL5188649
CHEMBL5191433
CHEMBL5189696
CHEMBL5178008
CHEMBL5187401
CHEMBL5189150
CHEMBL5171003
CHEMBL5185094
CHEMBL5185979
CHEMBL5170481
CHEMBL5204579
CHEMBL5177598
CHEMBL5185064
CHEMBL5202735
CHEMBL5185197
CHEMBL5177302
CHEMBL1214186
CHEMBL1214186
CHEMBL5190736
CHEMBL5187027
CHEMBL5191284
CHEMBL5187062
CHEMBL5184585
CHEMBL5188979
CHEMBL5177564
CHEMBL5202165
CHEMBL5192323
CHEMBL5193661
CHEMBL5172484
CHEMBL5202168
CHEMBL5194556
CHEMBL5170364
CHEMBL5177086
CHEMBL5183479
CHEMBL5193299
CHEMBL5184016
CHEMBL5198745
CHEMBL5203554
CHEMBL5188357
CHEMBL5183136
CHEMBL5189663
CHEMBL5184680
CHEMBL5191009
CHEMBL5184035
CHEMBL5201737
CHEMBL5196801
CHEMBL5174185
CHEMBL5175665
CHEMBL5205703
CHEMBL5177226
CHEMBL5185303
CHEMBL5180071
CHEMBL5172622
CHEMBL5209543
CHEMBL5198062
CHEMBL5199430
CHEMBL5179631
CHEMBL5188783
CHEMBL5178643
CHEMBL5190060
CHEMBL5180417
CHEMBL5189699
CHEMBL5172047
CHEMBL5171293
CHEMBL5182182
CHEMBL5197848
CHEMBL5171724
CHEMBL5205014
CHEMBL5209179
CHEMBL5170187
CHEMBL5205847
CHEMBL5175369
CHEMBL5208016
CHEMBL5207499
CHEMBL5205491
CHEMBL5174398
CHEMBL5175792
CHEMBL5171649
CHEMBL5201279
CHEMBL5199753
CHEMBL5175460
CHEMBL5169443
CHEMBL5199371
CHEMBL5169770
CHEMBL5191530
CHEMBL5220835
CHEMBL5218876
CHEMBL5219917
CHEMBL5219492
CHEMBL5219984
CHEMBL5220472
CHEMBL5220572
CHEMBL5220285
CHEMBL5218940
CHEMBL5219523
CHEMBL5219370
CHEMBL5218995
CHEMBL5220774
CHEMBL5220147
CHEMBL5220933
CHEMBL5219346
CHEMBL5219362
CHEMBL5218677
CHEMBL5219870
CHEMBL5219054
CHEMBL5218716
CHEMBL5220123
CHEMBL5220574
CHEMBL5220471
CHEMBL5220452
CHEMBL5220196
CHEMBL5220377
CHEMBL5219749
CHEMBL5218884
CHEMBL5220641
CHEMBL5286417
CHEMBL4796938
CHEMBL4764751
CHEMBL51085
CHEMBL964
CHEMBL3545157
CHEMBL460499
CHEMBL9470
CHEMBL406050
CHEMBL5290702
CHEMBL5271003
CHEMBL2380760
CHEMBL231813
CHEMBL4796938
CHEMBL4764751
CHEMBL4850298
CHEMBL3427166
CHEMBL3427167
CHEMBL5287345
CHEMBL304784
CHEMBL5290927
CHEMBL5290282
CHEMBL5267069
CHEMBL5270743
CHEMBL5271977
CHEMBL5288729
CHEMBL590
CHEMBL274056
CHEMBL164
CHEMBL5283004
CHEMBL5281998
CHEMBL5278950
CHEMBL5287918
CHEMBL5267414
CHEMBL5287068
CHEMBL4802135
CHEMBL490822
CHEMBL5205750
CHEMBL5195364
CHEMBL5193976
CHEMBL218394
CHEMBL5276480
CHEMBL5276875
CHEMBL5171771
CHEMBL5275051
CHEMBL64925
CHEMBL5266148
CHEMBL318779
CHEMBL4441971
CHEMBL5075209
CHEMBL5267356
CHEMBL468553
CHEMBL5289700
CHEMBL4096388
CHEMBL5283687
CHEMBL5288812
CHEMBL5287202
CHEMBL5270421
CHEMBL5288669
CHEMBL51085
CHEMBL5280925
CHEMBL5290840
CHEMBL5279145
CHEMBL5273811
CHEMBL5266355
CHEMBL5179454
CHEMBL3916514
CHEMBL99313
CHEMBL5291321
CHEMBL416639
CHEMBL1716371
CHEMBL5274000
CHEMBL45152
CHEMBL5280903
CHEMBL5271510
CHEMBL594248
CHEMBL3326854
CHEMBL5284680
CHEMBL5272459
CHEMBL5281399
CHEMBL5278945
CHEMBL5284676
CHEMBL228623
CHEMBL5279962
CHEMBL5279597
CHEMBL5281483
CHEMBL5279136
CHEMBL5286682
CHEMBL151
CHEMBL50
CHEMBL265502
CHEMBL4526128
CHEMBL5280512
CHEMBL460499
CHEMBL284861
CHEMBL964
CHEMBL9470
CHEMBL406050
CHEMBL5268979
CHEMBL4796938
CHEMBL4764751
CHEMBL4441971
CHEMBL5277714
CHEMBL5075209
CHEMBL8260
CHEMBL318779
CHEMBL5266148
CHEMBL204813
CHEMBL525084
CHEMBL5269476
CHEMBL5281602
CHEMBL377937
CHEMBL1770312
CHEMBL464006
CHEMBL549695
CHEMBL403516
CHEMBL8260
CHEMBL9470
CHEMBL403516
CHEMBL8260
CHEMBL406050
CHEMBL460499
CHEMBL51085
CHEMBL964
CHEMBL5280654
CHEMBL18786
CHEMBL51085
CHEMBL460499
CHEMBL9470
CHEMBL964
CHEMBL406050
CHEMBL3545157
CHEMBL8260
CHEMBL1448
CHEMBL76
CHEMBL729
CHEMBL4441971
CHEMBL5075209
CHEMBL5267069
CHEMBL5275426
CHEMBL5275166
CHEMBL5270743
CHEMBL5277900
CHEMBL5288153
CHEMBL5267952
CHEMBL5290856
CHEMBL5278216
CHEMBL5274687
CHEMBL5282049
CHEMBL5278207
CHEMBL5281031
CHEMBL5290455
CHEMBL5284630
CHEMBL5274857
CHEMBL5286696
CHEMBL5273500
CHEMBL5287318
CHEMBL5288416
CHEMBL5269547
CHEMBL5282244
CHEMBL5269544
CHEMBL5195325
CHEMBL5275295
CHEMBL5270522
CHEMBL5276490
CHEMBL5286331
CHEMBL5286326
CHEMBL5287690
CHEMBL5287688
CHEMBL5284199
CHEMBL4764751
CHEMBL4796938
CHEMBL5277063
CHEMBL5288267
CHEMBL5271624
CHEMBL5095608
CHEMBL3559293
CHEMBL5289335
CHEMBL5267356
CHEMBL468553
CHEMBL5266355
CHEMBL3655715
CHEMBL5283181
CHEMBL4779667
CHEMBL5195364
CHEMBL5270064
CHEMBL4552531
CHEMBL4068618
CHEMBL51085
CHEMBL4783878
CHEMBL5179454
CHEMBL4079667
CHEMBL99313
CHEMBL1435753
CHEMBL1336959
CHEMBL4060715
CHEMBL1394251
CHEMBL98386
CHEMBL45016
CHEMBL5277713
CHEMBL3219171
CHEMBL45152
CHEMBL2391913
CHEMBL297304
CHEMBL5280783
CHEMBL1710047
CHEMBL5274064
CHEMBL5266148
CHEMBL318779
CHEMBL1096283
CHEMBL212218
CHEMBL5290841
CHEMBL8260
CHEMBL92708
CHEMBL5286815
CHEMBL5279125
CHEMBL5291407
CHEMBL5291013
CHEMBL5287352
CHEMBL4796938
CHEMBL4764751
CHEMBL5267069
CHEMBL5075209
CHEMBL5173559
CHEMBL4850298
CHEMBL2315036
CHEMBL5082224
CHEMBL5278228
CHEMBL490820
CHEMBL5173274
CHEMBL5075209
CHEMBL4764751
CHEMBL5195325
CHEMBL5283942
CHEMBL5173274
CHEMBL4802135
CHEMBL5274314
CHEMBL5274314
CHEMBL5284419
CHEMBL5288475
CHEMBL5276871
CHEMBL5285814
CHEMBL5269736
CHEMBL5266928
CHEMBL5283003
CHEMBL5282313
CHEMBL5270638
CHEMBL5284820
CHEMBL5277777
CHEMBL5275803
CHEMBL5272656
CHEMBL5290811
CHEMBL5270863
CHEMBL5288572
CHEMBL5276507
CHEMBL5280670
CHEMBL5288939
CHEMBL5274679
CHEMBL5290148
CHEMBL5286093
CHEMBL5290924
CHEMBL5274265
CHEMBL5269801
CHEMBL5279877
CHEMBL418052
CHEMBL376902
CHEMBL5282983
CHEMBL495231
CHEMBL523052
CHEMBL5285762
CHEMBL468553
CHEMBL1339340
CHEMBL5280472
CHEMBL2311694
CHEMBL1405735
CHEMBL2311695
CHEMBL222769
CHEMBL468553
CHEMBL225515
CHEMBL222234
CHEMBL222840
CHEMBL221518
CHEMBL385315
CHEMBL446118
CHEMBL223094
CHEMBL374164
CHEMBL372816
CHEMBL373658
CHEMBL221519
CHEMBL5269595
CHEMBL2311694
CHEMBL510559
CHEMBL5278309
CHEMBL5274912
CHEMBL1082333
CHEMBL4289483
CHEMBL5288969
CHEMBL5272843
CHEMBL5280630
CHEMBL5279101
CHEMBL5279748
CHEMBL4802135
CHEMBL5283975
CHEMBL5266964
CHEMBL5286307
CHEMBL5282079
CHEMBL5275584
CHEMBL3427166
CHEMBL5275584
CHEMBL4065616
CHEMBL5281103
CHEMBL5268256
CHEMBL5434703
CHEMBL5401883
CHEMBL5435659
CHEMBL5397356
CHEMBL5396631
CHEMBL5435034
CHEMBL5409319
CHEMBL5406957
CHEMBL5403352
CHEMBL5410610
CHEMBL5395936
CHEMBL5075209
CHEMBL4796938
CHEMBL5076204
CHEMBL5191060
CHEMBL5195325
CHEMBL5270743
CHEMBL5400701
CHEMBL5411271
CHEMBL5402227
CHEMBL5439916
CHEMBL5403340
CHEMBL5419985
CHEMBL4802135
CHEMBL5403964
CHEMBL5438575
CHEMBL5409804
CHEMBL5414443
CHEMBL8260
CHEMBL164
CHEMBL1488059
CHEMBL5398303
CHEMBL5428557
CHEMBL5402852
CHEMBL5405232
CHEMBL5426704
CHEMBL5398507
CHEMBL5406478
CHEMBL5406269
CHEMBL5409259
CHEMBL5439420
CHEMBL4802135
CHEMBL549695
CHEMBL5408904
CHEMBL5414278
CHEMBL5435801
CHEMBL5410072
CHEMBL5426936
CHEMBL5412640
CHEMBL5427912
CHEMBL5440578
CHEMBL5401448
CHEMBL5400721
CHEMBL549695
CHEMBL5427912
CHEMBL5426970
CHEMBL5419959
CHEMBL5433524
CHEMBL5406733
CHEMBL5405589
CHEMBL5433349
CHEMBL5440163
CHEMBL5415120
CHEMBL5433293
CHEMBL5426613
CHEMBL5439320
CHEMBL5408912
CHEMBL5426354
CHEMBL5393926
CHEMBL5436494
CHEMBL5405557
CHEMBL5405150
CHEMBL5424235
CHEMBL5434476
CHEMBL5402239
CHEMBL5424499
CHEMBL5428994
CHEMBL5414988
CHEMBL5413385
CHEMBL5434471
CHEMBL5402510
CHEMBL5404972
CHEMBL5414071
CHEMBL5422084
CHEMBL5436896
CHEMBL5421859
CHEMBL5396481
CHEMBL5399690
CHEMBL5420595
CHEMBL5421178
CHEMBL5438553
CHEMBL5421269
CHEMBL4850298
CHEMBL3427166
CHEMBL3427166
CHEMBL4796938
CHEMBL5395482
CHEMBL5415051
CHEMBL5421800
CHEMBL5397586
CHEMBL358279

### **Iterate *canonical_smiles* to a list**

In [54]:
canonical_smiles = []
for i in df2.canonical_smiles:
  print(i)
  canonical_smiles.append(i)

Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1
Cc1c(-c2cnccn2)ssc1=S
O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1
O=C(O[C@@H]1Cc2c(O)cc(O)cc2O[C@@H]1c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1
O=C1C=Cc2cc(Br)ccc2C1=O
CC(CN1CC(=O)NC(=O)C1)N1CC(=O)NC(=O)C1
Nc1ccc2cc3ccc(N)cc3nc2c1
CCOC(=O)Cc1ccc(-c2ccccc2)cc1
O=[N+]([O-])c1ccc(Sc2cccc[n+]2[O-])c2nonc12
CCCCCCNC(=O)n1cc(F)c(=O)[nH]c1=O
O=C1C(Cl)=C(N2CCOCC2)C(=O)N1c1ccc(Cl)c(Cl)c1
CN1CCN(C(=O)c2ccc(-c3ccc4c(C=O)c(O)ccc4c3)s2)CC1
NC(CO)C(=O)NNCc1ccc(O)c(O)c1O
O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc(O)c12
CCN1CCN(C(c2ccc(C(F)(F)F)cc2)c2ccc3cccnc3c2O)CC1
Cn1sc(=O)n(Cc2ccccc2)c1=O
Oc1cc2c(cc1O)C(c1ccccc1)CNCC2
COC(=O)CC[C@H](NC(=O)[C@H](CC(=O)OC)NC(=O)OCc1ccccc1)C(=O)N[C@H](C(=O)N[C@@H](CC(=O)OC)C(=O)CF)C(C)C
Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1
Oc1cc2c(cc1C(c1ccc(C(F)(F)F)cc1)N1CCOCC1)OCO2
Sc1nnc(Nc2ccccc2)s1
Cc1ccc(C)c(-n2sc3cc(F)ccc3c2=O)c1
[O-][n+]1ccccc1S
O=C(CCl)c1ccccc1
c1ccc2sc(SSc3nc4ccccc4s3)nc2c1
O=C(CC1Sc2ncnn2C1=O)Nc1ccc(Br)cc1
CC(C)(C)OC(=O)NCCc1nnc(S(=O)(=O)Cc2ccc(Cl)cc2Cl)o1
Nc1ccc(O)c2ncccc12
CCOC(=O)c1c(N)sc(-c2ccccc2)c1C
Cc1cc(C)cc(N2C(=O)CC(Sc3nc[nH]n3)C2=O)c1
Cc1ccc(S(=O)(=O)N[C@@H](Cc2ccccc2)C(=O)CCl)cc1
Cc1ccc(-n2sc(=O)n(Cc3ccc(F)cc3)c2=O)cc1
Sc1nnnn1-c1ccccc1
Nc1nc(S)c2ncn(C3OC(CO)C(O)C3O)c2n1
O=c1c(O)cccc2cc(O)c(O)c(O)c12
C/C=C1\C(OC2OC(CO)C(O)C(O)C2O)OC=C(C(=O)OC)C1CC(=O)OCCc1ccc(O)c(O)c1
C=C1C(=O)[C@]23[C@H](O)[C@H]1CC[C@@H]2[C@@]12CO[C@]3(O)C[C@@H]1C(C)(C)CC[C@@H]2O
None
O=C(O)c1cc(O)c2c(c1)[C@H]([C@H]1c3cc(C(=O)O)cc(O)c3C(=O)c3c(O[C@@H]4O[C@H](CO)[C@@H](O)[C@H](O)[C@H]4O)cccc31)c1cccc(O[C@@H]3O[C@H](CO)[C@@H](O)[C@H](O)[C@H]3O)c1C2=O
COCCCOc1ccnc(C[S+]([O-])c2nc3ccccc3[n-]2)c1C.[Na+]
COc1ccc2[nH]c([S+]([O-])Cc3ncc(C)c(OC)c3C)nc2n1
[O-][S+](c1ccccc1)c1ccc2nnnn2n1
CCC(C)SSc1ncc[nH]1
Cl.NC(CO)C(=O)NNCc1ccc(O)c(O)c1O
C[C@@](Cc1ccc(O)c(O)c1)(NN)C(=O)O
O=C1C2CC=CCC2C(=O)N1SC(Cl)(Cl)Cl
CC(Cc1ccc(O)c(O)c1)C(C)Cc1ccc(O)c(O)c1
Br.Oc1cc2c(cc1O)C(c1ccccc1)CNCC2
None
Cc1ccccc1N(C)C(=O)c1ccc([S+]([O-])c2nccs2)c([N+](=O)[O-])c1
O=c1cc(-c2ccc(O)cc2)oc2cc(O)cc(O)c12
O=C1c2c(O)cc(O)cc2O[C@H](c2cc(O)c(O)c(O)c2)[C@H]1O
Cc1ccc(-n2sc(=O)n(Cc3ccc(F)cc3)c2=O)cc1
CN(C)CCNc1nc2cc(O)ccc2c2c1C(=O)c1ccccc1-2
CN1CC[C@@]2(C)c3cc(O)ccc3N(C)[C@@H]12.O=C(O)/C=C/C(=O)O
CC(C)c1cc(CNc2nc(Nc3cc(C4CC4)[nH]n3)cc(N3CCN(C)CC3)n2)on1
Cc1ccc(S(=O)(=O)/C=C/C#N)cc1
[O-][n+]1ccccc1[S-].[O-][n+]1ccccc1[S-].[Zn+2]
O=C(/C=C/c1ccc(O)c2c1[C@@H](C(=O)O[C@H](Cc1ccc(O)c(O)c1)C(=O)O)[C@H](c1ccc(O)c(O)c1)O2)O[C@H](Cc1ccc(O)c(O)c1)C(=O)O
O=C(/C=C/c1ccc(O)c(O)c1)O[C@H](Cc1ccc(O)c(O)c1)C(=O)O
None
COc1cc(C(=S)N2CCOCC2)ccc1O
O=C(O)c1ccc(SSc2ccc(C(=O)O)cn2)nc1
CN(C)C(=S)SSC(=S)N(C)C
O=c1c2ccccc2[se]n1-c1ccccc1
C/N=c1/nc(-c2ccccc2)n(-c2ccccc2)s1
C[C@@H]1O[C@@H](Oc2c(-c3cc(O)c(O)c(O)c3)oc3cc(O)cc(O)c3c2=O)[C@@H](O)[C@H](O)[C@H]1O
Cl.Oc1cc2c(cc1O)[C@H]1c3ccccc3CN[C@@H]1CC2
Nc1nnc(Sc2ncc([N+](=O)[O-])s2)s1
CCN(CC)C(=S)SSC(=S)N(CC)CC
O=C1C=CC(=O)C2=C1C1c3ccccc3C2c2ccccc21
O=[N+]([O-])C(Br)(CO)CO
CC(C)Nc1cccnc1N1CCN(C(=O)c2cc3cc(NS(C)(=O)=O)ccc3[nH]2)CC1.CS(=O)(=O)O
O=C1C=Cc2cc(Br)ccc2C1=O
C[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](OCCc3ccc(O)c(O)c3)O[C@H](CO)[C@H]2OC(=O)/C=C/c2ccc(O)c(O)c2)[C@H](O)[C@H](O)[C@H]1O
CN(C)C(=S)SC(=S)N(C)C
Oc1ccc2ccccc2c1SSc1c(O)ccc2ccccc12
CCC(=O)OCN1C(=O)C=CC1=O
CC[C@H](CO)Nc1nc(NCc2ccc(-c3ccccn3)cc2)c2ncn(C(C)C)c2n1
CC(C)N(CCC(=O)c1ccc2ccccc2c1)Cc1ccccc1
O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc(O)c12
CC(C)(C)c1ccc(S(=O)(=O)/C=C/C#N)cc1
Oc1c(I)cc(I)c(O)c1I
CCn1c(-c2nonc2N)nc2cncc(CNC3CCNCC3)c21
CCc1ccc(/C=C/C(=O)Nc2ccc(C(C)=O)cc2)o1
O=C(O)CCCCCCCCCCCCCCc1ccc(I)cc1
Oc1cc(CNC(=S)/C=C/c2cc(O)c(O)c(Br)c2)cc(O)c1O
N#CSc1cc(SC#N)c(N)nc1N
Sc1nc2ccccc2s1
O=C(O[C@@H]1Cc2c(O)cc(O)cc2O[C@@H]1c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1
None
CNC(=O)ON(C(C)=O)C(=O)NC
c1ccc2sc(SNC3CCCCC3)nc2c1
O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O
Nc1ccc2cc3ccc(N)cc3nc2c1.Nc1ccc2cc3ccc(N)cc3nc2c1.O=S(=O)(O)O
COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(/C(CO)=N/NC(=O)CCCCCN1C(=O)C=CC1=O)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1
None
O=c1cc(-c2ccccc2)oc2cc(O)c(O)c(O)c12
COc1cccc(C(=O)CCN[C@@H](C)[C@H](O)c2ccccc2)c1.Cl
O=[N+]([O-])c1cnc(Sc2nnc(O)n2-c2ccc3c(c2)OCCO3)s1
None
CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3.CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3.Cl.Cl.O
Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2
O=C1C(Cl)=C(N2CCOCC2)C(=O)N1c1ccc(Cl)c(Cl)c1
N.S=C(S)N1CCCC1
O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1
Cc1c(-c2cnccn2)ssc1=S
O=C(O)[C@@H](S)[C@@H](S)C(=O)O
COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12
C=CC(=O)c1ccc2ccccc2c1
C[n+]1c2cc(N)ccc2cc2ccc(N)cc21.[Cl-]
Nc1ccc(S(=O)(=O)[N-]c2ncccn2)cc1.[Ag+]
None
None
CC(C)C[C@H](NC(=O)[C@@H](NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1
CCOC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](NC(=O)OCc1ccccc1)C(C)C
O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)C(=O)NC(C)C
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@H](C=O)C[C@@H]1CCNC1=O
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)O
COc1cccc2[nH]c(C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C(=O)CO)cc12
C[C@@H](OC(C)(C)C)[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1CCCCC1)C(=O)N[C@H](C=O)C[C@@H]1CCNC1=O
O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)O
CC(C)(C)C(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)O
CCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CC(C)C[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCC[C@H](NC(=O)[C@@H]1[C@H]2CCC[C@H]2CN1C(=O)[C@@H](NC(=O)[C@@H](NC(=O)c1cnccn1)C1CCCCC1)C(C)(C)C)C(=O)C(=O)NC1CC1
CC(=O)N[C@@H](CO)C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](C)C(=O)N[C@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCC(N)=O)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](Cc1ccccc1)C(N)=O)C(C)C)[C@@H](C)O
N=C(N/N=C/c1ccccc1O)c1nonc1NCNc1nonc1C(=N)N/N=C/c1ccccc1O
COc1cc(C(NC2=NC(=O)C(CC(=O)Nc3ccc(C(=O)O)cc3)S2)c2c(O)[nH]c(=O)[nH]c2=O)ccc1O
COc1cc(C(NC2=NC(=O)C(CC(=O)Nc3ccc(C(=O)O)cc3)S2)c2c(O)[nH]c(=O)[nH]c2=O)ccc1O
N=C(N/N=C/c1ccccc1O)c1nonc1NCNc1nonc1C(=N)N/N=C/c1ccccc1O
Cn1cc(SCC(=O)NCc2ccccc2)c2ccccc21
Cn1cc(SCC(=O)N(Cc2ccccc2)Cc2ccccc2)c2ccccc21
CN(C)CCOc1ccc(CNC(=O)CSc2cn(C)c3ccccc23)cc1
COc1ccccc1CNC(=O)CSc1cn(C)c2ccccc12
Cn1cc(SCC(=O)NCc2ccc(Cl)c(Cl)c2)c2ccccc21
O=C(CSc1c[nH]c2ccccc12)NCc1ccccc1
O=C(CSc1c[nH]c2ccccc12)NCc1ccc(C(F)(F)F)cc1
CN(C)CCOc1ccc(CNC(=O)CSc2c[nH]c3ccccc23)cc1
COc1ccccc1CN(C)C(=O)CSc1c[nH]c2ccccc12
C[C@@H](NC(=O)CSc1c[nH]c2ccccc12)c1ccccc1
COc1ccccc1CNC(=O)CSc1c[nH]c2cccc(Br)c12
O=C(CSc1c[nH]c2cccc(Br)c12)NCc1ccc(Cl)c(Cl)c1
COc1ccccc1CNC(=O)CSc1c[nH]c2ccc(Br)cc12
O=C(CSc1c[nH]c2ccc(Br)cc12)NCc1ccc(Cl)c(Cl)c1
COc1ccccc1CNC(=O)CSc1c[nH]c2cc(Br)ccc12
O=C(CSc1c[nH]c2cc(Br)ccc12)NCc1ccc(Cl)c(Cl)c1
COc1ccccc1CNC(=O)CSc1c[nH]c2c(Br)cccc12
O=C(CSc1c[nH]c2c(Br)cccc12)NCc1ccc(Cl)c(Cl)c1
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1
CN(Cc1ccccc1)C(=O)CSc1c[nH]c2cccc(Br)c12
CN(Cc1ccccc1)C(=O)CSc1c[nH]c2c(Br)cccc12
O=C(CSc1c[nH]c2c(Br)cccc12)N(Cc1ccccc1)Cc1ccccc1
O=C(CSc1c[nH]c2ccccc12)N(Cc1ccccc1)Cc1ccccc1
CN(Cc1ccccc1)C(=O)CSc1c[nH]c2ccccc12
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1
COc1ccccc1CNC(=O)CSc1c[nH]c2c(-c3ccccc3)cccc12
O=C(CSc1c[nH]c2cccc(Br)c12)N(Cc1ccccc1)Cc1ccccc1
CCOc1ccccc1CN(OC)C(=O)CSc1c[nH]c2cccc(Br)c12
O=C(CSc1c[nH]c2ccccc12)N(Cc1ccccc1)Cc1ccccc1
CN(Cc1ccccc1)C(=O)CSc1c[nH]c2ccccc12
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1
COc1ccccc1CNC(=O)CSc1c[nH]c2c(-c3ccccc3)cccc12
O=C(CSc1c[nH]c2cccc(Br)c12)N(Cc1ccccc1)Cc1ccccc1
CCOc1ccccc1CN(OC)C(=O)CSc1c[nH]c2cccc(Br)c12
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CCCCC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NC2CC2)c1=O
O=C(/C=C/c1ccccc1)N[C@H](CC1CCCCC1)C(=O)N[C@H](C[C@@H]1CCNC1=O)C(=O)C(=O)NCc1ccccc1
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CCCCC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NC2CC2)c1=O
O=C(/C=C/c1ccccc1)N[C@H](CC1CCCCC1)C(=O)N[C@H](C[C@@H]1CCNC1=O)C(=O)C(=O)NCc1ccccc1
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1
CCCCCCNC(=O)n1cc(F)c(=O)[nH]c1=O
O=c1c2ccccc2[se]n1-c1ccccc1
CC(C)=CC[C@@H](O)C1=CC(=O)c2c(O)ccc(O)c2C1=O
CCN(CC)C(=S)SSC(=S)N(CC)CC
CCC(C)SSc1ncc[nH]1
O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1
O=c1cc(-c2ccccc2)oc2cc(O)c(O)c(O)c12
O=c1cc(-c2ccccc2)oc2cc(O)c(O)c(O)c12
O=C(O)[C@H]1O[C@@H](Oc2cc3oc(-c4ccccc4)cc(=O)c3c(O)c2O)[C@H](O)[C@@H](O)[C@@H]1O
CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)[O-].[Na+]
CSCC[C@H](C=O)NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](CC(C)C)NC(C)=O
CCC[C@@H](NC(=O)[C@@H](CC(C)C)NC(=O)OCc1ccccc1)C(=O)C(=O)NCc1ccccn1
O=C(/C=C/c1ccccc1)N[C@H](CC1CCCCC1)C(=O)N[C@H](C[C@@H]1CCNC1=O)C(=O)C(=O)NCc1ccccc1
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CCCCC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NC2CC2)c1=O
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1
CCCC[C@H](NC(=O)[C@@H]1[C@@H]2[C@H](CN1C(=O)[C@@H](NC(=O)NC1(CS(=O)(=O)C(C)(C)C)CCCCC1)C(C)(C)C)C2(C)C)C(=O)C(=O)NC1CC1
CC(C)C[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(C)=O
CCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1
CCCCCCNC(=O)n1cc(F)c(=O)[nH]c1=O
O=c1c2ccccc2[se]n1-c1ccccc1
CC(C)=CC[C@@H](O)C1=CC(=O)c2c(O)ccc(O)c2C1=O
CCN(CC)C(=S)SSC(=S)N(CC)CC
CCC(C)SSc1ncc[nH]1
O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1
O=C(O)[C@H]1O[C@@H](Oc2cc3oc(-c4ccccc4)cc(=O)c3c(O)c2O)[C@H](O)[C@@H](O)[C@@H]1O
CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)[O-].[Na+]
CSCC[C@H](C=O)NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](CC(C)C)NC(C)=O
CCC[C@@H](NC(=O)[C@@H](CC(C)C)NC(=O)OCc1ccccc1)C(=O)C(=O)NCc1ccccn1
O=C(/C=C/c1ccccc1)N[C@H](CC1CCCCC1)C(=O)N[C@H](C[C@@H]1CCNC1=O)C(=O)C(=O)NCc1ccccc1
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CCCCC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NC2CC2)c1=O
CC(C)(C)OC(=O)Nc1cccn([C@H](CC2CC2)C(=O)N[C@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1
CCCC[C@H](NC(=O)[C@@H]1[C@@H]2[C@H](CN1C(=O)[C@@H](NC(=O)NC1(CS(=O)(=O)C(C)(C)C)CCCCC1)C(C)(C)C)C2(C)C)C(=O)C(=O)NC1CC1
CC(C)C[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(C)=O
CCC[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)NC(=O)OCc1ccccc1
CCC[C@@H](NC(=O)[C@@H](CC(C)C)NC(=O)OCc1ccccc1)C(=O)C(=O)NCc1ccccn1
CSCC[C@H](C=O)NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](CC(C)C)NC(C)=O
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)[O-].[Na+]
CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C
O=c1cc(-c2ccccc2)oc2cc(O)c(O)c(O)c12
O=C(O)[C@H]1O[C@@H](Oc2cc3oc(-c4ccccc4)cc(=O)c3c(O)c2O)[C@H](O)[C@@H](O)[C@@H]1O
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1
O=C[C@@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1
Cc1ccc(N)cc1C(=O)N[C@@H](C)c1cccc2ccccc12
CC(=O)Nc1ccc(C)c(C(=O)N[C@@H](C)c2cccc3ccccc23)c1
Cc1ccccc1C(=O)NC(C)c1ccc2ccccc2c1
COc1ccc(CNC(=O)C2CCN(Cc3cccc4ccccc34)CC2)cc1
COc1ccc(-c2cc(=O)c3c(O)c(OC)c(O[C@@H]4O[C@H](CO[C@@H]5O[C@@H](C)[C@H](O)[C@@H](O)[C@H]5O)[C@@H](O)[C@H](O)[C@H]4O)cc3o2)cc1
C[C@@H]1O[C@@H](O[C@H]2[C@H](Oc3cc(O)c4c(=O)cc(-c5ccc(O)cc5)oc4c3)O[C@H](CO)[C@@H](O)[C@@H]2O)[C@H](O)[C@H](O)[C@H]1O
O=c1c(O)c(-c2ccc(O)cc2)oc2c(O)c(O)cc(O)c12
C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C
O=C(/C=C/CCc1ccc(O)c(O)c1)CCc1ccc(O)c(O)c1
C=C1CC[C@@H]2[C@](C)(CO)[C@H](O)CC[C@@]2(C)[C@@H]1C/C=C1/C(=O)OC[C@H]1O
CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)[O-].[Na+]
CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)C2(C)C
COc1cccc2[nH]c(C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C(=O)CO)cc12
O=C(NCc1ccco1)C1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1.O=C(O)C(F)(F)F
O=C(NCc1cccs1)[C@@H]1CN(C(=O)c2cccnc2)CCN1c1ccc(Cl)c(Cl)c1
Cn1cnc(Cn2c(=O)[nH]/c(=N\c3cc4cn(C)nc4cc3Cl)n(Cc3cc(F)c(F)cc3F)c2=O)n1
O=C(c1cc(=O)[nH]c(=O)[nH]1)N1CCN(c2ccc(Cl)c(Cl)c2)CC1
O=C(NCc1cccs1)[C@@H]1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1Cc1ccc(Cl)cc1Cl
O=C(NCc1cccs1)[C@@H]1CN(C(=O)c2cncc3ccccc23)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1ccco1)C1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1cccs1)C1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1ccco1)[C@H]1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1ccco1)[C@@H]1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1cccs1)[C@@H]1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1c1ccc(Cl)c(Cl)c1
O=C(NCc1ccco1)C1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1Cc1ccc(Cl)cc1Cl
O=C(NCc1ccco1)[C@@H]1CN(C(=O)c2cc(=O)[nH]c(=O)[nH]2)CCN1Cc1ccc(Cl)cc1Cl
O=C(c1cc(=O)[nH]c(=O)[nH]1)N1CCN(c2ccc(Cl)c(Cl)c2)CC1
O=c1[nH]cc(-c2cc(-c3cc(Cl)cc(OCc4ccccc4Cl)c3)c(=O)n(-c3cccnc3)c2)c(=O)[nH]1
C[C@H](NC(=O)[C@@H](c1cccnc1)N(C(=O)CCl)c1ccc(-n2cccc2)cc1)c1ccccc1
C[C@H](NC(=O)[C@@H](c1cccnc1)N(C(=O)C(Cl)Cl)c1ccc(-c2ccccc2)cc1)c1ccccc1
CCS(=O)(=O)N1CCC([C@@H](C)n2c(C)c(C(=O)NCc3c(OC)cc(C)[nH]c3=O)c3ccccc32)CC1
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2cccs2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(C(=O)NCC3CCO3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN3CC[C@H](O)C3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN3CC[C@@H](O)C3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@@H]3CCOC3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@H]3CCOC3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CNC[C@H]3CCCO3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(C(=O)O)s2)c1
COC(=O)c1ccc(-c2cccc([C@@H](C)NC(=O)c3cc(NC4CNC4)ccc3C)c2)s1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CNC3CCC(O)C3)s2)c1
CC(=O)NCc1ccc(-c2cccc([C@@H](C)NC(=O)c3cc(NC4CNC4)ccc3C)c2)s1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CNC3CCNC3=O)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@@H]3CC[C@H](O)C3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@@H]3CC[C@@H](O)C3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@H]3CC[C@@H](O)C3)s2)c1
Cc1ccc(NC2CNC2)cc1C(=O)N[C@H](C)c1cccc(-c2ccc(CN[C@H]3CC[C@H](O)C3)s2)c1
Cc1ccc(N(C)C2CNC2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(N(C)C2CNC2)cc1C(=O)N[C@H](C)c1nccc2ccccc12
Cc1ccc(NC2CCNCC2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(NC2CCN(C)CC2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(NC(=O)C2CCNCC2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
CCCCC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
C=CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
Cc1ccc(NC(=O)NC(N)=O)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(NC(=O)Oc2ccc([N+](=O)[O-])cc2)cc1C(=O)N[C@H](C)c1cccc2ccccc12
CCCCNC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
Nc1cc(C(=O)Nc2cccc3ccccc23)cc(C(F)(F)F)c1
Cc1cc(N)ccc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1ccc(N(C)C)cc1C(=O)N[C@H](C)c1cccc2ccccc12
Cc1cc(NS(C)(=O)=O)ccc1C(=O)N[C@H](C)c1cccc2ccccc12
C[C@H](c1cccc2ccccc12)N1Cc2ccccc2C1
C[C@@H](NC(=O)c1ccccc1Cl)c1cccc2ccccc12
Cc1ccsc1C(=O)N[C@H](C)c1cccc2ccccc12
CC(c1ccccc1Cl)N(C)Cc1cc(O)ccc1Cl
Cc1ccccc1[C@@H](C)N(C)Cc1cc(O)ccc1Cl
C[C@H](c1cccc2ccccc12)N(C)Cc1cccc2[nH]ccc12
C[C@H](c1cccc2ccccc12)N(C)Cc1ccc2[nH]ncc2c1
C[C@H](c1cccc2ccccc12)N(C)Cc1c[nH]c2ccccc12
Cc1ccc(O)cc1CN(C)[C@H](C)c1cccc2ccccc12
Cc1cc(O)ccc1CN(C)[C@H](C)c1cccc2ccccc12
C[C@H](c1cccc2ccccc12)N(C)Cc1ccc(O)cc1Cl
COc1cc(O)ccc1CN(C)[C@H](C)c1cccc2ccccc12
Cc1ccc(N)cc1CN(C)[C@H](C)c1cccc2ccccc12
C[C@H](c1cccc2ccccc12)N(C)Cc1ccc(O)cc1
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(F)c2)CC1
CC(=O)Nc1cccc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)c1
COc1cc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)ccn1
CC(=O)Nc1cc(F)cc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)c1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCC2CCN(C)CC2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(NC(=O)CN(C)C)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(NC(=O)N3CCN(C)CC3)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cc(F)cc(NC(=O)CN(C)C)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cc(F)cc(NC(=O)N3CCN(C)CC3)c2)CC1
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(F)c2)CC1
CC(=O)Nc1cccc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)c1
COc1cc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)ccn1
CC(=O)Nc1cc(F)cc(CNC(=O)C2CCN([C@H](C)c3cccc4ccccc34)CC2)c1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCC2CCN(C)CC2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(NC(=O)CN(C)C)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cccc(NC(=O)N3CCN(C)CC3)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cc(F)cc(NC(=O)CN(C)C)c2)CC1
C[C@H](c1cccc2ccccc12)N1CCC(C(=O)NCc2cc(F)cc(NC(=O)N3CCN(C)CC3)c2)CC1
CC(C)(C)OC(=O)Nc1cccn([C@@H](CC2CC2)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
CC(C)(C)OC(=O)Nc1cccn(C(CC2CC2)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
CC(C)(C)OC(=O)Nc1cccn(C(CC2CC2)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)C(=O)NCc2ccccc2)c1=O
COc1cccc2[nH]c(C(=O)N[C@@H](CC(C)C)C(=O)NN(C[C@@H]3CCNC3=O)C(=O)[C@H](F)Cl)cc12
CC(C)C[C@H](NC(=O)c1cc2c(F)cccc2[nH]1)C(=O)NN(C[C@@H]1CCNC1=O)C(=O)[C@H](F)Cl
CC(C)C[C@H](NC(=O)c1cc2c(F)cccc2[nH]1)C(=O)NN(C[C@@H]1CCNC1=O)C(=O)[C@@H](F)Cl
CC(C)C[C@H](NC(=O)c1cc2c(F)cccc2[nH]1)C(=O)NN(C[C@H]1CCNC1=O)C(=O)[C@H](F)Cl
COc1cccc2[nH]c(C(=O)N[C@@H](CC(C)C)C(=O)NN(C[C@H]3CCNC3=O)C(=O)[C@H](F)Cl)cc12
CC(C)C[C@H](NC(=O)c1cc2c(F)cccc2[nH]1)C(=O)NN(C[C@H]1CCNC1=O)C(=O)[C@@H](F)Cl
CC(=O)N(C[C@@H]1CCNC1=O)NC(=O)[C@H](CC(C)C)NC(=O)c1cc2c(F)cccc2[nH]1
COc1cccc2[nH]c(C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C(=O)CO)cc12
CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)C2(C)C
O=C(CSc1nc2cc(Cl)ccc2n1Cc1ccccc1)N1CCNC1=O
O=C(CSc1nc2cc(Cl)ccc2n1Cc1ccccc1)N1CCOC1=O
CC(C)(C)c1ccc2c(c1)nc(SCC(=O)N1CCOC1=O)n2Cc1ccccc1
O=C1NCCN1C(=O)C(Cc1ccccc1)Sc1nc2cc(Cl)ccc2n1Cc1ccccc1
Cc1ccc2c(c1)nc(SC(Cc1ccccc1)C(=O)N1CCNC1=O)n2Cc1ccccc1
O=C1OCCN1C(=O)C(Cc1ccccc1)Sc1nc2cc(Cl)ccc2n1Cc1ccccc1
Cc1ccc2c(c1)nc(SC(Cc1ccccc1)C(=O)N1CCOC1=O)n2Cc1ccccc1
CC(C)(C)c1ccc2c(c1)nc(SC(Cc1ccccc1)C(=O)N1CCOC1=O)n2Cc1ccccc1
O=C1OCCN1C(=O)C(Cc1ccco1)Sc1nc2cc(Cl)ccc2n1Cc1ccccc1
O=C1OCCN1C(=O)C(Cc1ccco1)Sc1nc2ccc(Cl)cc2n1Cc1ccccc1
COc1ccc2nc(SC(Cc3ccco3)C(=O)N3CCOC3=O)n(Cc3ccccc3)c2c1
O=C1OCCN1C(=O)C(Cc1ccco1)Sc1nc2ccc(O)cc2n1Cc1ccccc1
O=C(CSc1nc2cc(Cl)c(Cl)cc2n1Cc1ccccc1)N1CCOC1=O
COc1cc2c(cc1Cl)nc(SCC(=O)N1CCOC1=O)n2Cc1ccccc1
O=C(CSc1nc2cc(Cl)c(O)cc2n1Cc1ccccc1)N1CCOC1=O
O=C1OCCN1C(=O)C(Cc1ccco1)Sc1nc2cc(Cl)c(Cl)cc2n1Cc1ccccc1
COc1cc2c(cc1Cl)nc(SC(Cc1ccco1)C(=O)N1CCOC1=O)n2Cc1ccccc1
O=C1OCCN1C(=O)C(Cc1ccco1)Sc1nc2cc(Cl)c(O)cc2n1Cc1ccccc1
O=C(CSc1nc2cc(Cl)ccc2n1Cc1ccccc1)N1CCNC1=O
CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C
COCCn1c(C(=O)NCC(O)c2ccccc2)nc2ccccc2c1=O

### **Iterate *standard_value* to a list**

In [55]:
standard_value = []
for i in df2.standard_value:
  print(i)
  standard_value.append(i)

390.0
210.0
80.0
1580.0
40.0
3190.0
360.0
200.0
100.0
160.0
4530.0
1330.0
140.0
220.0
150.0
140.0
2800.0
10.0
1600.0
540.0
390.0
20.0
50.0
190.0
160.0
2040.0
4220.0
2050.0
3190.0
3170.0
1370.0
150.0
2360.0
1080.0
4580.0
3380.0
2570.0
210.0
1590.0
740.0
970.0
1120.0
140.0
140.0
3550.0
670.0
2590.0
2630.0
1740.0
1870.0
3020.0
180.0
230.0
2990.0
1990.0
1490.0
820.0
2460.0
3420.0
3860.0
240.0
1320.0
240.0
50.0
30.0
980.0
3660.0
1050.0
30.0
220.0
240.0
420.0
3990.0
160.0
4540.0
940.0
510.0
290.0
840.0
580.0
400.0
840.0
330.0
2070.0
4950.0
2250.0
480.0
410.0
1740.0
720.0
10.0
1330.0
770.0
4380.0
830.0
580.0
3820.0
20.0
2350.0
300.0
10.0
520.0
220.0
1140.0
210.0
150.0
620.0
1720.0
4360.0
1240.0
4980.0
750.0
880.0
1930.0
94.0
286.0
14.0
23.0
65.0
42.0
34.0
8.0
9.0
53.0
40.0
31.0
31.0
4130.0
10690.0
30.0
3140.0
3900.0
4810.0
11470.0
71000.0
110.0
450.0
85.0
63.0
26920.0
12300.0
8910.0
9820.0
7500.0
6810.0
7940.0
9080.0
7640.0
6680.0
8710.0
7210.0
10720.0
9770.0
10010.0
8710.0
7080.0
4550.0
1560.0
4730.0
20890.0
7080.0
3350.0
4550.0
1190.0
1650.0
3760.0
1110.0
4010.0
5370.0
3110.0
2180.0
3850.0
1890.0
180.0
2390.0
180.0
2390.0
180.0
670.0
124930.0
1820.0
670.0
15750.0
9350.0
21390.0
1550.0
940.0
939.72
6410.0
4130.0
30.0
970.0
450.0
180.0
2390.0
670.0
53.0
40.0
5730.0
3900.0
10690.0
8600.0
3140.0
125025.9
1819.7
669.88
15739.83
9354.06
21379.62
1548.82
6412.1
4130.48
29.99
970.51
449.78
179.89
2387.81
669.88
52.97
39.99
5727.96
3899.42
10690.55
8590.14
3140.51
450.0
970.0
30.0
4130.0
940.0
6410.0
40.0
53.0
2400.0
5000.0
23500.0
100700.0
38000.0
27000.0
33000.0
4200.0
4100.0
15000.0
33.0
75.0
5.0
8.0
0.4
0.013
5.1
0.44
0.44
0.79
0.61
2.98
0.35
0.4
0.59
0.48
4200.0
18.0
50.0
430.0
7300.0
1610.0
1010.0
590.0
820.0
700.0
640.0
330.0
620.0
760.0
970.0
810.0
170.0
370.0
640.0
210.0
430.0
113.0
250.0
2400.0
56000.0
600.0
700.0
800.0
12700.0
6400.0
5100.0
7000.0
16800.0
43200.0
7500.0
10000.0
10000.0
7600.0
15000.0
42000.0
7290.0
6670.0
620.0
660.0
670.0
870.0
900.0
800.0
580.0
990.0
670.0
6970.0
2640.0
2690.0
4320.0
1760.0
3750.0
1370.0
820.0
800.0
440.0
2670.0
1750.0
2000.0
1850.0
1130.0
2160.0
1520.0
580.0
780.0
260.0
120.0
380.0
670.0
9.5
3.8
28.0
4.8
15.6
464.0
332.0
1.7
0.79
24200.0
62200.0
35100.0
29900.0
32400.0
26700.0
36500.0
29500.0
14900.0
52900.0
53900.0
55800.0
29500.0
52500.0
35800.0
30800.0
27700.0
46100.0
24200.0
12100.0
54000.0
19.0
11.0
4.8
5.2
150.0
60.0
36.0
13.0
16.0
77.0
49.0
350.0
8.4
650.0
530.0
160.0
52.0
66.0
30.0
8.5
15.0
33.0
60.0
47.0
105.0
17.9
23.0
9.3
40.0
360.0
620.0
75.0
370.0
720.0
120.0
23.0
17.0
26.0
180.0
150.0
22.0
45.0
59.0
97.0
120.0
720.0
66.0
4200.0
8000.0
10000.0
13900.0
6100.0
56900.0
52300.0
17200.0
1700.0
38500.0
59800.0
10300.0
9400.0
7700.0
21000.0
10.0
19.0
14.0
9.0
5.0
10.0
15.0
5.0
10.0
780.0
6.0
4.0
14.0
2.0
12.0
9.0
360.0
100.0
140.0
260.0
190.0
13.0
40.0
60.0
19.5
49.0
13.7
24.0
14.0
9.1
18.9
4600.0
3660.0
75010.0
1500.0
1500.0
1500.0
7500.0
8100.0
5100.0
5600.0
5600.0
420.0
1410.0
46.0
34.0
8.0
540.0
87.0
5.0
17.0
17.0
1200.0
53.0
2.0
7.0
4.0
3.0
14.0
2.0
4.0
143.0
624.0
60.0
72.3
54.7
159.0
349.0
91.4
147.0
1220.0
281.0
316.0
481.0
34.4
250.0
235.0
454.0
11.4
87.6
2030.0
18.1
288.0
15.5
13.7
14.4
20.6
551.0
117.0
166.0
255.0
190.0
125.0
88.9
313.0
34.2
2350.0
2080.0
4030.0
710.0
670.0
1340.0
900.0
53.0
40.0
30.0
940.0
6410.0
1100.0
340.0
670.0
240.0
10000.0
10000.0
2260.0
240.0
260.0
34000.0
260.0
600.0
4350.0
1390.0
1789.0
1336.0
590.0
1571.0
260.0
530.0
390.0
610.0
440.0
2690.0
7290.0
6670.0
670.0
670.0
2300.0
5100.0
6400.0
7000.0
12700.0
810.0
2100.0
11000.0
3760.0
6680.0
3990.0
1660.0
1460.0
500.0
1000.0
100.0
72000.0
560.0
2470.0
5630.0
2210.0
1650.0
7240.0
1700.0
2200.0
3100.0
66000.0
13160.0
16080.0
15680.0
17510.0
94.0
230.0
98.0
5400.0
8000.0
2020.0
236.0
256.0
339.0
263.0
1255.0
578.0
1885.0
990.0
2067.0
1038.0
1288.0
25.69
49.55
27.95
52.5
15.24
37.81
27.37
7520.0
858.0
3889.0
374.0
373.0
277.0
271.0
209.0
321.0
298.0
1497.0
12320.0
6928.0
3436.0
2044.0
1338.0
3275.0
543.0
357.0
281.0
196.0
230.0
295.0
249.0
592.0
307.0
173.0
255.0
295.0
221.0
199.0
257.0
404.0
1409.0
234.0
173.0
172.0
153.0
640.0
565.0
197.0
148.0
1426.0
285.0
21280.0
300.0
25020.0
17500.0
10760.0
8080.0
9690.0
10880.0
17530.0
9090.0
4140.0
5810.0
7090.0
8760.0
10400.0
10300.0
1550.0
4000.0
5390.0
4050.0
8140.0
4690.0
1570.0
32530.0
40590.0
25390.0
10000.0
24560.0
5780.0
5440.0
42760.0
6180.0
850.0
670.0
670.0
53.0
4130.0
30.0
15.0
940.0
2500.0
31.0
10.0
8.0
44.0
19.0
27.0
27.0
540.0
1800.0
630.0
190.0
190.0
160.0
400.0
380.0
190.0
140.0
150.0
180.0
150.0
300.0
120.0
310.0
334.8
250.0
210.0
2293.0
220.2
1571.3
230.0
388.3
680.0
253.0
539.9
165.2
116.8
286.7
328.0
333.5
153.1
286.6
224.2
392.7
524.02
1767.0
416.0
443.1
10977.0
490.0
6400.0
7900.0
15300.0
11.2
6800.0
138000.0
38900.0
125300.0
9600.0
2700.0
61.0
69.0
440.0
48.0
93.0
260.0
100.0
100.0
100.0
100.0
2390.0
670.0
1600.0
180.0
310.0
2800.0
400.0
5100.0
92.0
0.27
530.0
670.0
8.0
30.0
10960.0
670.0
120.0
990.0
40.0
670.0
390.0
256.0
260.0
1390.0
94.0
200.0
280.0
510.0
560.0
660.0
670.0
810.0
940.0
960.0
1050.0
1480.0
1810.0
1970.0
2140.0
2390.0
2470.0
2510.0
2540.0
2680.0
3860.0
4100.0
4930.0
4970.0
5370.0
5460.0
5700.0
5820.0
7270.0
7490.0
7810.0
8130.0
10960.0
12090.0
13240.0
21880.0
35100.0
190.0
64.1
21.9
20.0
12.5
86.3
63.5
6.4
1.0
125.5
4.0
32.9
19.0
14.0
22.1
71.5
19.5
1500.0
17.0
61150.0
33060.0
29460.0
9060.0
6440.0
19320.0
11390.0
85580.0
57670.0
53810.0
58910.0
68160.0
5650.0
66800.0
35770.0
18500.0
14170.0
11970.0
13820.0
8540.0
2460.0
9820.0
4790.0
10260.0
3320.0
10000.0
11230.0
7390.0
5250.0
4290.0
2720.0
6730.0
2780.0
8890.0
6650.0
5830.0
3660.0
8280.0
3310.0
1550.0
1810.0
10230.0
5390.0
4710.0
10680.0
5500.0
1040.0
17660.0
5440.0
3200.0
7810.0
4060.0
7120.0
5920.0
5790.0
5350.0
5320.0
10490.0
6720.0
19090.0
36070.0
8500.0
54.0
13.0
8600.0
96.0
14100.0
5100.0
1400.0
3500.0
2100.0
5000.0
3589.0
4400.0
2900.0
342.0
244.0
146.0
516.0
80.0
38.0
44.0
5300.0
899.0
1010.0
514.0
960.0
19.0
13020.0
482.0
344.0
442.0
100.0
56.0
114.0
80.0
30.0
278.0
360.0
6600.0
26100.0
5800.0
9200.0
7400.0
16900.0
3600.0
1600.0
35300.0
13300.0
31100.0
10200.0
9000.0
7900.0
5200.0
3000.0
9700.0
6600.0
45700.0
5300.0
2800.0
2300.0
4100.0
42100.0
700.0
10100.0
24200.0
600.0
500.0
22900.0
3300.0
850.0
1150.0
650.0
260.0
260.0
680.0
450.0
750.0
760.0
1250.0
1200.0
360.0
290.0
380.0
410.0
350.0
290.0
240.0
240.0
320.0
390.0
410.0
2500.0
3050.0
3650.0
2500.0
410.0
500.0
830.0
760.0
520.0
490.0
4950.0
4050.0
330.0
340.0
180.0
170.0
290.0
290.0
310.0
260.0
280.0
300.0
260.0
280.0
140.0
100.0
1900.0
1710.0
390.0
370.0
270.0
300.0
310.0
310.0
180.0
150.0
290.0
270.0
270.0
250.0
820.0
1030.0
740.0
780.0
670.0
50.0
40.0
670.0
670.0
670.0
670.0
670.0
670.0
260.0
11390.0
9840.0
10700.0
53.0
40.0
400.0
190.0
45.0
45.0
970.0
16.0
15.2
7.6
17.2
2860.0
86320.0
7960.0
490.0
200.0
430.0
80.0
56.0
530.0
14.0
830.0
19.2
55.0
34.2
27.95
15.24
1590.0
51.0
54.0
8.5
105.0
7400.0
450.0
8600.0
180.0
670.0
151.0
81.0
47200.0
157500.0
20700.0
300.0
260.0
160.0
4900.0
670.0
363.0
345.0
467.0
824.0
74.0
110.0
320.0
190.0
1000.0
410.0
30.0
320.0
130.0
4300.0
8800.0
6000.0
5300.0
6100.0
5600.0
8500.0
4100.0
5800.0
7000.0
7100.0
2000.0
44100.0
15900.0
3400.0
4600.0
6900.0
260.0
27600.0
1550.0
1820.0
2500.0
9350.0
15750.0
21390.0
670.0
53.0
40.0
180.0
2390.0
670.0
50600.0
2000.0
1000.0
7200.0
6700.0
13900.0
4800.0
5300.0
35200.0
33500.0
800.0
24300.0
980.0
1600.0
3800.0
5160.0
670.0
670.0
670.0
24100.0
11410.0
124930.0
670.0
1820.0
15750.0
9350.0
21390.0
1550.0
940.0
280.0
7280.0
9120.0
180.0
670.0
7.6
7.6
9.2
17.2
17.4
19.7
30.0
34.7
36.2
69.1
93.5
153.1
195.6
298.8
375.0
378.2
525.9
748.5
12.4
13.0
13.2
13.3
14.5
15.2
16.5
18.5
19.0
37.2
43.3
50.8
52.1
453.0
40.0
53.0
200.0
230.0
410.0
450.0
30.0
650.0
151.0
81.0
74.0
130.0
150.0
240.0
260.0
330.0
350.0
410.0
520.0
650.0
110.0
130.0
170.0
230.0
330.0
360.0
380.0
390.0
410.0
410.0
480.0
490.0
630.0
660.0
730.0
780.0
910.0
450.0
970.0
260.0
300.0
600.0
940.0
2430.0
2510.0
37840.0
197730.0
6490.0
2370.0
53.0
40.0
7600.0
670.0
670.0
400.0
190.0
680.0
72.0
320.0
8.1
670.0
40.0
15.2
0.2
8.1
3.1
46280.0
46290.0
249990.0
102440.0
60520.0
54560.0
62030.0
90480.0
46870.0
6710.0
14260.0
66920.0
79620.0
35220.0
39320.0
66960.0
21240.0
19660.0
19640.0
96930.0
76790.0
19370.0
5270.0
6470.0
14740.0
7480.0
14150.0
16510.0
220.0
9190.0
2500.0
17200.0
18200.0
4300.0
500.0
4300.0
2500.0
4890.0
2200.0
28100.0
63.0
500.0
65.0
50.0
60.0
2700.0
53000.0
70000.0
28000.0
64000.0
3400.0
600.0
2900.0
57000.0
1500.0
200.0
28000.0
75000.0
6100.0
13000.0
4100.0
7500.0
7500.0
42790.0
36.82
41.65
54.64
22.83
18.06
22.42
8060.0
460.0
3220.0
1640.0
4700.0
6380.0
160.0
140.0
11900.0
890.0
2800.0
160.0
3000.0
4700.0
11000.0
7100.0
230.0
900.0
53.0
34.0
19.0
15.2
17.2
135.0
551.0
165.0
47.0
356.0
43.0
14.0
34.0
104.0
50.0
77.0
900.0
600.0
2214.0
1849.0
478.0
4601.0
2899.0
1057.0
3333.0
322.0
2641.0
524.0
3961.0
33.0
1.113
4.117
33.22
0.066
27.58
4.094
0.852
0.039
6.073
12.83
13.95
3.496
165.21
70.0
90.0
210.0
450.0
490.0
200.0
310.0
330.0
350.0
190.0
200.0
140.0
130.0
170.0
270.0
150.0
170.0
320.0
310.0
300.0
310.0
310.0
240.0
460.0
340.0
170.0
170.0
190.0
210.0
300.0
280.0
220.0
230.0
200.0
120.0
290.0
320.0
380.0
410.0
190.0
53.0
770.0
440.0
1120.0
530.0
300.0
364.0
287.0
459.0
528.0
233.0
490.0
322.0
417.0
356.0
268.0
550.0
339.0
53.0
670.0
2500.0
72.0
47200.0
157000.0
12.02
26.92
177.83
21.38
21.0
23.0
22.39
178.0
34673.69
35000.0
12.0
27.0
1460.0
22400.0
9360.0
1360.0
20.0
1412.54
22387.21
9332.54
1348.96
22.91
4000.0
8.0
990.0
120.0
670.0
2500.0
9350.0
30.0
3900.0
1500.0
260.0
6810.0
9840.0
6500.0
11390.0
8600.0
96.0
13.0
1110.0
3450.0
3770.0
5400.0
5610.0
8640.0
9920.0
1740.0
2990.0
960.0
490.0
600.0
400.0
10600.0
200.0
150.0
80.0
390.0
5800.0
1200.0
1240.0
2860.0
5600.0
2070.0
180.0
2390.0
670.0
70.0
110.0
8.0
27.0
2770.0
4080.0
180.0
200.0
80.0
30.0
180.0
70.0
2350.0
2080.0
11.0
3.0
50.0
40.0
30.0
3880.0
140.0
180.0
7.0
15.0
10760.0
1570.0
1550.0
250.0
750.0
430.0
80.0
700.0
600.0
500.0
4100.0
420.0
410.0
45.0
10960.0
6100.0
1550.0
1810.0
400.0
1443.0
5132.0
12760.0
435.0
6960.0
7706.0
554.0
8017.0
9797.0
365.0
2277.0
1867.0
1481.0
10530.0
1798.0
10588.0
11169.0
7635.0
8423.0
18285.0
1130.0
1541.0
2716.0
1372.0
966.0
15190.0
3565.0
5485.0
539.0
1370.0
4943.0
4086.0
385.0
970.0
2874.0
327.0
174.0
210.0
390.0
124.0
1365.0
949.0
290.0
124.0
274.0
83.0
205.0
236.0
271.0
207.0
117.0
1476.0
212.0
390.0
477.0
1005.0
290.0
386.0
692.0
107.0
239.0
100.0
284.0
131.0
502.0
466.0
14.8
76.3
16.1
81.1
28.8
24.0
34.7
36.5
35.4
34.5
33.7
34.8
60.1
160.0
22.0
23.4
28.1
101.0
55.0
20000.0
50000.0
6000.0
15000.0
14000.0
27000.0
25000.0
19000.0
2200.0
12000.0
31000.0
59000.0
60000.0
341000.0
62000.0
78000.0
127000.0
170000.0
3500.0
8000.0
12000.0
25000.0
11000.0
39000.0
32000.0
7000.0
4600.0
4700.0
15600.0
2200.0
7300.0
2040.0
900.0
900.0
23300.0
27400.0
52400.0
49000.0
38400.0
278.0
1.81
982.0
81.0
28.0
34.0
45.0
62.0
61.0
50.0
52.0
71.0
77.0
77.0
193.0
39980.0
143.0
323.0
124.0
136.0
165.0
118.0
373.0
582.0
462.0
252.0
78.0
409.0
302.0
206.0
191.0
655.0
448.0
2520.0
71890.0
880.0
2050.0
670.0
620.0
440.0
7197.0
7211.07
1350.0
21200.0
51.0
14400.0
6210.0
260.0
0.22
0.7
6.23
0.47
0.24
4196.0
20290.0
2.5
5.0
3350.0
5.3
53.0
29.0
74.0
53.0
56.0
110.0
98.0
400.0
560.0
510.0
25.0
25.0
30.0
22.0
49.0
990.0
39.0
25.0
41.0
2200.0
3600.0
1500.0
6000.0
1400.0
55.0
28.0
40.0
42.0
100.0
103.0
30.0
24380.0
23320.0
13340.0
9570.0
9120.0
5260.0
4520.0
3940.0
4520.0
5680.0
3730.0
9550.0
11500.0
10970.0
9060.0
7320.0
5150.0
3630.0
3360.0
3350.0
4450.0
4150.0
3310.0
6210.0
5110.0
3690.0
2550.0
2480.0
1920.0
1590.0
1670.0
2350.0
2050.0
2030.0
1020.0
4090.0
180.0
1840.0
6500.0
4400.0
35000.0
29000.0
39000.0
22000.0
2500.0
12000.0
290.0
500.0
330.0
340.0
16000.0
300.0
760.0
63.0
170.0
16.0
8.0
88.0
55.0
100.0
1590.0
280.0
44.0
28.0
9990.0
43.0
21.0
17.0
16.0
13.0
12.0
9.0
6.0
12.0
120.0
9000.0
360.0
19.0
4000.0
3408.0
2850.0
2180.0
573.0
468.0
383.0
187.0
130.0
274.0
62.0
17.3
9.5
25.6
2.8
1.2
3.5
2.1
2.07
1.3
0.72
40800.0
45700.0
6.0
6.0
6.0
7.0
6.0
7.0
270.0
250.0
210.0
320.0
350.0
210.0
170.0
440.0
400.0
90.0
9500.0
1300.0
400.0
1800.0
200.0
220.0
190.0
430.0
400.0
410.0
350.0
480.0
9600.0
5500.0
13.0
11.0
14.0
10.0
3270.0
7400.0
3680.0
44800.0
350.0
1020.0
30.0
15750.0
6100.0
16100.0
1100.0
4600.0
100.0
10.0
900.0
920.0
1000.0
480.0
35200.0
15500.0
6300.0
1300.0
15900.0
13300.0
13200.0
45000.0
163000.0
90000.0
134000.0
178000.0
201000.0
279000.0
181000.0
192000.0
7.4
6.5
7.7
7.4
7.0
5.0
41999.0
43056.0
121872.0
22960.0
13647.0
1022.0
1058.0
650.0
440.0
535.0
555.0
628.0
598.0
632.0
644.0
653.0
470.0
653.0
462.0
430.0
474.0
540.0
498.0
599.0
592.0
3430.0
44290.0
25257.0
37984.0
35766.0
58909.0
78355.0
61559.0
28285.0
66421.0
2270.0
68052.0
15162.0
11179.0
14906.0
30658.0
15016.0
97513.0
96596.0
35261.0
78425.0
74635.0
14186.0
12023.0
46460.0
46659.0
7859.0
6043.0
85214.0
96966.0
73741.0
86018.0
32486.0
24495.0
70879.0
76080.0
20662.0
21768.0
24841.0
20790.0
19483.0
21811.0
2730.0
2949.0
20196.0
24610.0
2066.0
2122.0
33219.0
34497.0
38017.0
40823.0
24672.0
24194.0
2589.0
3177.0
36636.0
33224.0
70212.0
81723.0
29582.0
31235.0
20566.0
20218.0
27379.0
29017.0
6825.0
7542.0
10309.0
9531.0
65277.0
71328.0
41212.0
38323.0
52149.0
62896.0
87945.0
92786.0
49309.0
60336.0
3474.0
3775.0
10641.0
12377.0
75220.0
99007.0
39188.0
40323.0
7569.0
7266.0
14566.0
18188.0
2784.0
3037.0
6387.0
6247.0
4201.0
4194.0
35815.0
41309.0
44506.0
43915.0
25018.0
27477.0
13886.0
15471.0
8187.0
8223.0
58260.0
59922.0
80286.0
93874.0
1921.0
2115.0
6357.0
8208.0
9045.0
8763.0
19870.0
20025.0
17695.0
19859.0
7291.0
8332.0
11265.0
13102.0
63771.0
49305.0
14513.0
14574.0
3778.0
4547.0
12088.0
10023.0
6574.0
5475.0
12220.0
10103.0
8537.0
10045.0
9410.0
7953.0
28881.0
34595.0
5196.0
6522.0
15952.0
22754.0
16299.0
21720.0
50132.0
58401.0
27312.0
32468.0
77115.0
68167.0
1809.0
1882.0
9067.0
13392.0
95327.0
25708.0
39932.0
55365.0
64688.0
1286.0
1165.0
989.0
54100.0
51166.0
38113.0
57461.0
37806.0
50419.0
38643.0
39459.0
25792.0
20661.0
522.0
522.0
436.0
66287.0
25682.0
1226.0
1059.0
1017.0
900.0
2968.0
3933.0
3174.0
383.0
361.0
2230.0
2253.0
46186.0
37198.0
29899.0
992.0
1005.0
83162.0
77592.0
5822.0
5927.0
2248.0
2443.0
700.0
722.0
34030.0
76435.0
72299.0
2278.0
1853.0
7830.0
6577.0
18677.0
17369.0
27831.0
31700.0
27170.0
24164.0
74645.0
71425.0
15356.0
16798.0
149.0
133.0
25299.0
25967.0
7157.0
7384.0
45705.0
44654.0
801.0
610.0
4555.0
4966.0
80690.0
94364.0
3007.0
2637.0
1841.0
1654.0
450.0
366.0
15261.0
14959.0
10072.0
11792.0
66031.0
20926.0
20592.0
72165.0
72010.0
34091.0
33797.0
4357.0
3816.0
7923.0
7709.0
786.0
865.0
79412.0
83634.0
728.0
692.0
5312.0
6501.0
1953.0
1966.0
3428.0
3072.0
68.0
74.0
92316.0
91831.0
396.0
378.0
2963.0
453.0
466.0
3114.0
3488.0
280.0
305.0
808.0
532.0
2570.0
2598.0
90037.0
93525.0
247.0
258.0
1523.0
1637.0
17769.0
22124.0
2524.0
2511.0
50867.0
55872.0
485.0
517.0
3453.0
3981.0
19314.0
18172.0
1844.0
2019.0
1072.0
1062.0
44431.0
50603.0
274.0
319.0
309.0
332.0
253.0
315.0
21897.0
18851.0
479.0
585.0
1186.0
1777.0
2676.0
2708.0
857.0
800.0
394.0
449.0
5810.0
7131.0
19155.0
16269.0
903.0
891.0
16730.0
18480.0
626.0
652.0
421.0
563.0
2985.0
3583.0
1858.0
1954.0
2093.0
2218.0
16109.0
14284.0
5769.0
7415.0
1066.0
1023.0
804.0
853.0
27578.0
34219.0
2562.0
3089.0
1079.0
1228.0
4224.0
3905.0
2151.0
2537.0
1507.0
1447.0
972.0
1024.0
423.0
473.0
1318.0
1530.0
5136.0
5848.0
2272.0
2616.0
2010.0
2065.0
905.0
1062.0
871.0
843.0
2506.0
2580.0
16591.0
17219.0
2974.0
3241.0
3841.0
3916.0
5595.0
8760.0
1789.0
1905.0
20454.0
19662.0
1136.0
1382.0
9528.0
10248.0
281.0
383.0
3279.0
3758.0
2794.0
1625.0
1634.0
1809.0
1074.0
1242.0
1851.0
2130.0
2709.0
2666.0
43948.0
39730.0
5160.0
4513.0
1190.0
1186.0
67731.0
67368.0
1299.0
1505.0
3018.0
2938.0
6200.0
6096.0
639.0
701.0
1697.0
2132.0
713.0
737.0
4972.0
4995.0
243.0
259.0
27372.0
25976.0
421.0
446.0
674.0
711.0
746.0
819.0
5342.0
4546.0
164.0
143.0
2691.0
2896.0
676.0
868.0
1187.0
961.0
10123.0
8667.0
213.0
206.0
330.0
341.0
3732.0
3000.0
2612.0
2710.0
282.0
269.0
411.0
493.0
469.0
6782.0
8836.0
8767.0
1173.0
1518.0
1404.0
892.0
1421.0
1290.0
699.0
883.0
832.0
538.0
616.0
618.0
757.0
962.0
864.0
998.0
1231.0
1124.0
416.0
475.0
383.0
2187.0
2452.0
2619.0
9282.0
10723.0
10116.0
8537.0
8993.0
9514.0
3252.0
3449.0
3569.0
40556.0
37565.0
26445.0
28876.0
1155.0
1347.0
1403.0
250.0
302.0
355.0
422.0
498.0
497.0
3485.0
5543.0
5190.0
3497.0
4099.0
4030.0
203.0
230.0
270.0
1043.0
1382.0
1310.0
8696.0
13554.0
17040.0
6078.0
306.0
31732.0
163.0
128.0
46.0
242.0
260.0
82.0
1118.0
326.0
25.0
2569.0
1197.0
1780.0
894.0
435.0
440.0
316.0
338.0
701.0
439.0
411.0
374.0
353.0
440.0
447.0
847.0
925.0
461.0
794.0
731.0
432.0
353.0
1102.0
317.0
406.0
649.0
516.0
384.0
402.0
374.0
289.0
506.0
262.0
224.0
632.0
28921.0
743.0
1537.0
20064.0
39.0
55.0
11659.0
11537.0
7292.0
11278.0
93.0
138.0
803.0
194.0
512.0
55738.0
36.0
54.0
39.0
54.0
27268.0
9976.0
17943.0
1251.0
1744.0
52.0
78.0
1014.0
1335.0
1357.0
1928.0
580.0
1147.0
1361.0
2016.0
2841.0
4417.0
72555.0
837.0
1336.0
639.0
1758.0
3681.0
7822.0
1361.0
3404.0
1146.0
2572.0
1098.0
2064.0
2943.0
5873.0
793.0
2001.0
954.0
1914.0
2104.0
4225.0
1970.0
5692.0
1295.0
2346.0
1094.0
2636.0
47158.0
10735.0
19669.0
1445.0
3272.0
43542.0
56.0
100.0
9980.0
22962.0
1322.0
1273.0
939.0
815.0
17844.0
13947.0
19303.0
19051.0
30827.0
40.0
29.0
283.0
156.0
312.0
59.0
7237.0
5891.0
678.0
611.0
35.0
19.0
30.0
792.0
829.0
629.0
543.0
866.0
790.0
695.0
623.0
1291.0
947.0
1391.0
1234.0
4420.0
4281.0
1597.0
1617.0
955.0
1044.0
633.0
594.0
25.0
41.0
414.0
502.0
96417.0
4146.0
16597.0
6894.0
19858.0
5756.0
17018.0
1687.0
3911.0
238.0
901.0
802.0
2138.0
3623.0
2350.0
313.0
187.0
20892.0
17698.0
1273.0
967.0
27708.0
23521.0
124.0
117.0
95.0
197.0
6222.0
4918.0
20457.0
17610.0
18.0
15.0
13.0
22250.0
4957.0
2327.0
3077.0
2416.0
120.0
110.0
246.0
23342.0
14094.0
10734.0
64.0
54.0
203.0
213.0
224.0
2242.0
1913.0
6453.0
5614.0
22.0
19.0
19.0
289.0
396.0
533.0
101.0
95.0
86868.0
18.0
16.0
15.0
204.0
197.0
288.0
50828.0
1865.0
1937.0
71.0
57.0
3156.0
2858.0
3789.0
65.0
66.0
479.0
316.0
72.0
454.0
100.0
85.0
409.0
455.0
145.0
150.0
604.0
628.0
28794.0
37604.0
28409.0
123.0
95.0
5363.0
961.0
1340.0
1077.0
163.0
154.0
30.0
30.0
133.0
191.0
235.0
24584.0
65.0
70.0
70.0
108.0
3902.0
6457.0
4275.0
4353.0
5376.0
4136.0
107.0
171.0
117.0
21.0
16.0
31.0
15.0
23.0
23.0
25.0
31.0
7011.0
4478.0
395.0
261.0
1065.0
574.0
28.0
14.0
32.0
13.0
28.0
28.0
24.0
36.0
12.0
11.0
322.0
241.0
288.0
36799.0
11620.0
743.0
68.0
134.0
33.0
64.0
52.0
90.0
50.0
73.0
181.0
39.0
79.0
57.0
143.0
1276.0
9145.0
19.0
34.0
17.0
29.0
34.0
27.0
35.0
15.0
328.0
264.0
122.0
75560.0
3145.0
54.0
107.0
14.0
26.0
10.0
20.0
22.0
27.0
29.0
1788.0
6735.0
24.0
48.0
38.0
52.0
35.0
60.0
47900.0
20.0
34.0
19.0
33.0
53.0
32.0
42.0
176.0
208.0
189.0
992.0
1166.0
100.0
90.0
156.0
241.0
3053.0
1673.0
50.0
46.0
40.0
48.0
78.0
242.0
334.0
360.0
114.0
63.0
52.0
85.0
58.0
60.0
85.0
62.0
106.0
94.0
68.0
116.0
478.0
308.0
538.0
82.0
114.0
244.0
49.0
54.0
94.0
60.0
69.0
414.0
419.0
74.0
63.0
112.0
1115.0
784.0
5557.0
4255.0
30.0
26.0
45.0
29.0
33.0
1560.0
770.0
2937.0
1557.0
30131.0
258.0
186.0
325.0
93.0
73.0
126.0
241.0
131.0
349.0
297.0
189.0
345.0
456.0
272.0
503.0
51.0
43.0
65.0
46.0
52.0
203.0
120.0
206.0
1791.0
46826.0
287.0
614.0
235.0
395.0
26454.0
38426.0
43824.0
29.0
38.0
37.0
43.0
51.0
47457.0
62908.0
59840.0
67353.0
1548.0
1442.0
3682.0
2567.0
794.0
1336.0
1899.0
1795.0
2849.0
982.0
24631.0
2245.0
110.0
57.0
6049.0
119.0
349.0
319.0
2343.0
1490.0
1614.0
9731.0
8119.0
1030.0
622.0
340.0
336.0
52128.0
10833.0
12.0
971.0
85.0
22793.0
10833.0
20.0
10.0
375.0
67.0
18970.0
1621.0
58.0
100600.0
113800.0
22700.0
35100.0
10700.0
70900.0
11200.0
11100.0
176500.0
59200.0
14400.0
10400.0
1700.0
7500.0
7600.0
96500.0
2100.0
200.0
200.0
100.0
100.0
1300.0
50200.0
200.0
4000.0
4200.0
11700.0
1800.0
600.0
900.0
31400.0
2100.0
20800.0
7700.0
4300.0

### **Combine the 4 lists into a dataframe**

In [56]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [57]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL480,Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1,active,390.0
1,CHEMBL178459,Cc1c(-c2cnccn2)ssc1=S,active,210.0
2,CHEMBL3545157,O=c1sn(-c2cccc3ccccc23)c(=O)n1Cc1ccccc1,active,80.0
3,CHEMBL297453,O=C(O[C@@H]1Cc2c(O)cc(O)cc2O[C@@H]1c1cc(O)c(O)...,intermediate,1580.0
4,CHEMBL4303595,O=C1C=Cc2cc(Br)ccc2C1=O,active,40.0
...,...,...,...,...
4876,CHEMBL6193634,COc1ccc(/C=N/NC(=O)c2ccc(CSc3cccc4cccnc34)cc2)cc1,active,960.0
4877,CHEMBL6191170,O=C(N/N=C/c1cc(F)c(F)cc1O)c1ccc(CSc2cccc3cccnc...,intermediate,2340.0
4878,CHEMBL6191510,O=C(N/N=C/c1cc(O)c(Br)c(O)c1)c1ccc(CSc2cccc3cc...,intermediate,2060.0
4879,CHEMBL6193155,O=C(N/N=C/c1cc([N+](=O)[O-])ccc1Cl)c1ccc(CSc2c...,active,280.0
4880,CHEMBL6188867,O=C(N/N=C/c1cc([N+](=O)[O-])ccc1Cl)c1ccc(CSc2c...,active,760.0

### **Alternative method**

In [ ]:
# selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
# df3 = df2[selection]
# pd.concat([df3,pd.Series(bioactivity_class)], axis=1)
# df3

Saves dataframe to CSV file

In [58]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [59]:
! ls -l

total 3916
-rw-r--r-- 1 root root 1770903 Oct  7 18:51 bioactivity_data.csv
-rw-r--r-- 1 root root 1770903 Oct  7 18:50 bioactivity_data_original.csv
-rw-r--r-- 1 root root  454885 Oct  7 18:52 bioactivity_preprocessed_data.csv
drwxr-xr-x 1 root root    4096 Oct  2 13:50 sample_data

Let's copy to the Google Drive

In [ ]:
#! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
# ! ls "/content/gdrive/My Drive/Colab Notebooks/data"

---